C:\Program Files\Sublime Text 3

C:\Users\nayana>mkdirdjangogirls
'mkdirdjangogirls' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\nayana>mkdir djangogirls

C:\Users\nayana>cd djangogirls

C:\Users\nayana\djangogirls> C:\Users\nayana\AppData\Local\Programs\Python\Python36\python -m venv myvenv

C:\Users\nayana\djangogirls>myvenv\Scripts\activate
(myvenv) C:\Users\nayana\djangogirls>pip install --upgrade pip
Could not fetch URL https://pypi.python.org/simple/pip/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
Requirement already up-to-date: pip in c:\users\nayana\djangogirls\myvenv\lib\site-packages

(myvenv) C:\Users\nayana\djangogirls>pip install django~=1.10.0
Collecting django~=1.10.0
  Could not fetch URL https://pypi.python.org/simple/django/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
  Could not find a version that satisfies the requirement django~=1.10.0 (from versions: )
No matching distribution found for django~=1.10.0

(myvenv) C:\Users\nayana\djangogirls>pip install --upgrade pip
Could not fetch URL https://pypi.python.org/simple/pip/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
Requirement already up-to-date: pip in c:\users\nayana\djangogirls\myvenv\lib\site-packages

(myvenv) C:\Users\nayana\djangogirls>pip install
You must give at least one requirement to install (see "pip help install")

(myvenv) C:\Users\nayana\djangogirls>pip install --upgrade pip
Could not fetch URL https://pypi.python.org/simple/pip/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
Requirement already up-to-date: pip in c:\users\nayana\djangogirls\myvenv\lib\site-packages

(myvenv) C:\Users\nayana\djangogirls>pip install --upgrade pip
Could not fetch URL https://pypi.python.org/simple/pip/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
Requirement already up-to-date: pip in c:\users\nayana\djangogirls\myvenv\lib\site-packages

(myvenv) C:\Users\nayana\djangogirls>pip install django~=1.10.0
Collecting django~=1.10.0
  Could not fetch URL https://pypi.python.org/simple/django/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
  Could not find a version that satisfies the requirement django~=1.10.0 (from versions: )
No matching distribution found for django~=1.10.0

(myvenv) C:\Users\nayana\djangogirls>pip install django~=1.10.0
Collecting django~=1.10.0
  Could not fetch URL https://pypi.python.org/simple/django/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
  Could not find a version that satisfies the requirement django~=1.10.0 (from versions: )
No matching distribution found for django~=1.10.0

(myvenv) C:\Users\nayana\djangogirls>pip install --upgrade pip
Could not fetch URL https://pypi.python.org/simple/pip/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
Requirement already up-to-date: pip in c:\users\nayana\djangogirls\myvenv\lib\site-packages

(myvenv) C:\Users\nayana\djangogirls>python -m pip install django~=1.10.0
Collecting django~=1.10.0
  Could not fetch URL https://pypi.python.org/simple/django/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
  Could not find a version that satisfies the requirement django~=1.10.0 (from versions: )
No matching distribution found for django~=1.10.0

(myvenv) C:\Users\nayana\djangogirls>python -m pip install django~=1.10.0
Collecting django~=1.10.0
  Could not fetch URL https://pypi.python.org/simple/django/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
  Could not find a version that satisfies the requirement django~=1.10.0 (from versions: )
No matching distribution found for django~=1.10.0

(myvenv) C:\Users\nayana\djangogirls>python -m pip install django~=1.10.0
Collecting django~=1.10.0
  Could not fetch URL https://pypi.python.org/simple/django/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
  Could not find a version that satisfies the requirement django~=1.10.0 (from versions: )
No matching distribution found for django~=1.10.0

(myvenv) C:\Users\nayana\djangogirls>python -m pip install django~=1.10.0
Collecting django~=1.10.0
  Could not fetch URL https://pypi.python.org/simple/django/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
  Could not find a version that satisfies the requirement django~=1.10.0 (from versions: )
No matching distribution found for django~=1.10.0

(myvenv) C:\Users\nayana\djangogirls>python -m pip install django~=1.10.0
Collecting django~=1.10.0
  Could not fetch URL https://pypi.python.org/simple/django/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
  Could not find a version that satisfies the requirement django~=1.10.0 (from versions: )
No matching distribution found for django~=1.10.0

(myvenv) C:\Users\nayana\djangogirls>pip install --upgrade pip
Could not fetch URL https://pypi.python.org/simple/pip/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
Requirement already up-to-date: pip in c:\users\nayana\djangogirls\myvenv\lib\site-packages

(myvenv) C:\Users\nayana\djangogirls>python
Python 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()

(myvenv) C:\Users\nayana\djangogirls>python -m pip install django~=1.10.1
Collecting django~=1.10.1
  Could not fetch URL https://pypi.python.org/simple/django/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
  Could not find a version that satisfies the requirement django~=1.10.1 (from versions: )
No matching distribution found for django~=1.10.1

(myvenv) C:\Users\nayana\djangogirls>pip install django~=1.
Invalid requirement: 'django~=1.'
Traceback (most recent call last):
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\packaging\requirements.py", line 92, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\pyparsing.py", line 1617, in parseString
    raise exc
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\pyparsing.py", line 1607, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\pyparsing.py", line 3376, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\pyparsing.py", line 1383, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\pyparsing.py", line 3164, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pip._vendor.pyparsing.ParseException: Expected stringEnd (at char 6), (line:1, col:7)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\req\req_install.py", line 82, in __init__
    req = Requirement(req)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\packaging\requirements.py", line 96, in __init__
    requirement_string[e.loc:e.loc + 8]))
pip._vendor.packaging.requirements.InvalidRequirement: Invalid requirement, parse error at "'~=1.'"


(myvenv) C:\Users\nayana\djangogirls>pip install django~=1.10.1
Collecting django~=1.10.1
  Could not fetch URL https://pypi.python.org/simple/django/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
  Could not find a version that satisfies the requirement django~=1.10.1 (from versions: )
No matching distribution found for django~=1.10.1

(myvenv) C:\Users\nayana\djangogirls>pip install django~=1.10.0
Collecting django~=1.10.0
  Could not fetch URL https://pypi.python.org/simple/django/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
  Could not find a version that satisfies the requirement django~=1.10.0 (from versions: )
No matching distribution found for django~=1.10.0

(myvenv) C:\Users\nayana\djangogirls>pip install django==1.10.0
Collecting django==1.10.0
  Could not fetch URL https://pypi.python.org/simple/django/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
  Could not find a version that satisfies the requirement django==1.10.0 (from versions: )
No matching distribution found for django==1.10.0

(myvenv) C:\Users\nayana\djangogirls>pip3 install django~=1.10.0
Collecting django~=1.10.0
  Could not fetch URL https://pypi.python.org/simple/django/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
  Could not find a version that satisfies the requirement django~=1.10.0 (from versions: )
No matching distribution found for django~=1.10.0

(myvenv) C:\Users\nayana\djangogirls>pip3 install django~=1.10.0
Collecting django~=1.10.0
  Could not fetch URL https://pypi.python.org/simple/django/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
  Could not find a version that satisfies the requirement django~=1.10.0 (from versions: )
No matching distribution found for django~=1.10.0

(myvenv) C:\Users\nayana\djangogirls>pip install django==1.10.0
Collecting django==1.10.0
  Could not fetch URL https://pypi.python.org/simple/django/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
  Could not find a version that satisfies the requirement django==1.10.0 (from versions: )
No matching distribution found for django==1.10.0

(myvenv) C:\Users\nayana\djangogirls>pip install Django~=1.10.0
Collecting Django~=1.10.0
  Could not fetch URL https://pypi.python.org/simple/django/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
  Could not find a version that satisfies the requirement Django~=1.10.0 (from versions: )
No matching distribution found for Django~=1.10.0

(myvenv) C:\Users\nayana\djangogirls>pip install Django==1.10.0
Collecting Django==1.10.0
  Could not fetch URL https://pypi.python.org/simple/django/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
  Could not find a version that satisfies the requirement Django==1.10.0 (from versions: )
No matching distribution found for Django==1.10.0

(myvenv) C:\Users\nayana\djangogirls>pip install Django
Collecting Django
  Could not fetch URL https://pypi.python.org/simple/django/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
  Could not find a version that satisfies the requirement Django (from versions: )
No matching distribution found for Django

(myvenv) C:\Users\nayana\djangogirls>pip install django
Collecting django
  Could not fetch URL https://pypi.python.org/simple/django/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
  Could not find a version that satisfies the requirement django (from versions: )
No matching distribution found for django

(myvenv) C:\Users\nayana\djangogirls>ping google.com

Pinging google.com [172.217.26.174] with 32 bytes of data:
Reply from 172.217.26.174: bytes=32 time=73ms TTL=56
Reply from 172.217.26.174: bytes=32 time=69ms TTL=56
Reply from 172.217.26.174: bytes=32 time=69ms TTL=56

Ping statistics for 172.217.26.174:
    Packets: Sent = 3, Received = 3, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 69ms, Maximum = 73ms, Average = 70ms
Control-C
^C
(myvenv) C:\Users\nayana\djangogirls>python3
'python3' is not recognized as an internal or external command,
operable program or batch file.

(myvenv) C:\Users\nayana\djangogirls>python
Python 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()

(myvenv) C:\Users\nayana\djangogirls>pip install --upgrade pip
Could not fetch URL https://pypi.python.org/simple/pip/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
Requirement already up-to-date: pip in c:\users\nayana\djangogirls\myvenv\lib\site-packages

(myvenv) C:\Users\nayana\djangogirls>easy_install pip
Searching for pip
Best match: pip 9.0.1
Adding pip 9.0.1 to easy-install.pth file
Installing pip-script.py script to c:\users\nayana\djangogirls\myvenv\Scripts
Installing pip.exe script to c:\users\nayana\djangogirls\myvenv\Scripts
Installing pip3-script.py script to c:\users\nayana\djangogirls\myvenv\Scripts
Installing pip3.exe script to c:\users\nayana\djangogirls\myvenv\Scripts
Installing pip3.5-script.py script to c:\users\nayana\djangogirls\myvenv\Scripts
Installing pip3.5.exe script to c:\users\nayana\djangogirls\myvenv\Scripts

Using c:\users\nayana\djangogirls\myvenv\lib\site-packages
Processing dependencies for pip
Finished processing dependencies for pip

(myvenv) C:\Users\nayana\djangogirls>pip install Django==1.10.0
Collecting Django==1.10.0
  Could not fetch URL https://pypi.python.org/simple/django/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
  Could not find a version that satisfies the requirement Django==1.10.0 (from versions: )
No matching distribution found for Django==1.10.0

(myvenv) C:\Users\nayana\djangogirls>pip --version
pip 9.0.1 from c:\users\nayana\djangogirls\myvenv\lib\site-packages (python 3.6)

(myvenv) C:\Users\nayana\djangogirls>pip --version
Traceback (most recent call last):
  File "C:\Users\nayana\djangogirls\myvenv\Scripts\pip-script.py", line 6, in <module>
    from pkg_resources import load_entry_point
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pkg_resources\__init__.py", line 36, in <module>
    import email.parser
  File "C:\Users\nayana\AppData\Local\Programs\Python\Python36\lib\email\parser.py", line 12, in <module>
    from email.feedparser import FeedParser, BytesFeedParser
  File "C:\Users\nayana\AppData\Local\Programs\Python\Python36\lib\email\feedparser.py", line 27, in <module>
    from email._policybase import compat32
  File "C:\Users\nayana\AppData\Local\Programs\Python\Python36\lib\email\_policybase.py", line 9, in <module>
    from email.utils import _has_surrogates
  File "C:\Users\nayana\AppData\Local\Programs\Python\Python36\lib\email\utils.py", line 28, in <module>
    import random
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 764, in get_code
  File "<frozen importlib._bootstrap_external>", line 832, in get_data
KeyboardInterrupt

(myvenv) C:\Users\nayana\djangogirls>pip install Django==1.10.0
Collecting Django==1.10.0
  Could not fetch URL https://pypi.python.org/simple/django/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
  Could not find a version that satisfies the requirement Django==1.10.0 (from versions: )
No matching distribution found for Django==1.10.0

(myvenv) C:\Users\nayana\djangogirls>pip install -upgrade pip.

Usage:
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

no such option: -u

(myvenv) C:\Users\nayana\djangogirls>pip install --upgrade pip
Could not fetch URL https://pypi.python.org/simple/pip/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
Requirement already up-to-date: pip in c:\users\nayana\djangogirls\myvenv\lib\site-packages

(myvenv) C:\Users\nayana\djangogirls>pip install django~=1.10.0
Collecting django~=1.10.0
  Could not fetch URL https://pypi.python.org/simple/django/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
  Could not find a version that satisfies the requirement django~=1.10.0 (from versions: )
No matching distribution found for django~=1.10.0

(myvenv) C:\Users\nayana\djangogirls>pip install django~=1.10.0 -vv
Config variable 'Py_DEBUG' is unset, Python ABI tag may be incorrect
Config variable 'WITH_PYMALLOC' is unset, Python ABI tag may be incorrect
Collecting django~=1.10.0
  1 location(s) to search for versions of django:
  * https://pypi.python.org/simple/django/
  Getting page https://pypi.python.org/simple/django/
  Looking up "https://pypi.python.org/simple/django/" in the cache
  No cache entry available
  Starting new HTTPS connection (1): pypi.python.org
  Could not fetch URL https://pypi.python.org/simple/django/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
  Could not find a version that satisfies the requirement django~=1.10.0 (from versions: )
Cleaning up...
No matching distribution found for django~=1.10.0
Exception information:
Traceback (most recent call last):
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\commands\install.py", line 324, in run
    requirement_set.prepare_files(finder)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\req\req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\req\req_set.py", line 554, in _prepare_file
    require_hashes
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\req\req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\index.py", line 514, in find_requirement
    'No matching distribution found for %s' % req
pip.exceptions.DistributionNotFound: No matching distribution found for django~=1.10.0
Looking up "https://pypi.python.org/pypi/pip/json" in the cache
No cache entry available
Starting new HTTPS connection (1): pypi.python.org
There was an error checking the latest version of pip
Traceback (most recent call last):
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\packages\urllib3\connectionpool.py", line 589, in urlopen
    self._prepare_proxy(conn)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\packages\urllib3\connectionpool.py", line 797, in _prepare_proxy
    conn.connect()
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\packages\urllib3\connection.py", line 289, in connect
    ssl_version=resolved_ssl_version)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\packages\urllib3\util\ssl_.py", line 308, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Users\nayana\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 401, in wrap_socket
    _context=self, _session=session)
  File "C:\Users\nayana\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 808, in __init__
    self.do_handshake()
  File "C:\Users\nayana\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 1061, in do_handshake
    self._sslobj.do_handshake()
  File "C:\Users\nayana\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 683, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\adapters.py", line 423, in send
    timeout=timeout
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\packages\urllib3\connectionpool.py", line 621, in urlopen
    raise SSLError(e)
pip._vendor.requests.packages.urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\utils\outdated.py", line 126, in pip_version_check
    headers={"Accept": "application/json"},
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\sessions.py", line 488, in get
    return self.request('GET', url, **kwargs)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\download.py", line 386, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\cachecontrol\adapter.py", line 47, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\adapters.py", line 497, in send
    raise SSLError(e, request=request)
pip._vendor.requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)

(myvenv) C:\Users\nayana\djangogirls>pip install django~=1.10.0 -vv
Config variable 'Py_DEBUG' is unset, Python ABI tag may be incorrect
Config variable 'WITH_PYMALLOC' is unset, Python ABI tag may be incorrect
Collecting django~=1.10.0
  1 location(s) to search for versions of django:
  * https://pypi.python.org/simple/django/
  Getting page https://pypi.python.org/simple/django/
  Looking up "https://pypi.python.org/simple/django/" in the cache
  No cache entry available
  Starting new HTTPS connection (1): pypi.python.org
  Could not fetch URL https://pypi.python.org/simple/django/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
  Could not find a version that satisfies the requirement django~=1.10.0 (from versions: )
Cleaning up...
No matching distribution found for django~=1.10.0
Exception information:
Traceback (most recent call last):
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\commands\install.py", line 324, in run
    requirement_set.prepare_files(finder)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\req\req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\req\req_set.py", line 554, in _prepare_file
    require_hashes
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\req\req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\index.py", line 514, in find_requirement
    'No matching distribution found for %s' % req
pip.exceptions.DistributionNotFound: No matching distribution found for django~=1.10.0
Looking up "https://pypi.python.org/pypi/pip/json" in the cache
No cache entry available
Starting new HTTPS connection (1): pypi.python.org
There was an error checking the latest version of pip
Traceback (most recent call last):
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\packages\urllib3\connectionpool.py", line 589, in urlopen
    self._prepare_proxy(conn)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\packages\urllib3\connectionpool.py", line 797, in _prepare_proxy
    conn.connect()
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\packages\urllib3\connection.py", line 289, in connect
    ssl_version=resolved_ssl_version)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\packages\urllib3\util\ssl_.py", line 308, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Users\nayana\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 401, in wrap_socket
    _context=self, _session=session)
  File "C:\Users\nayana\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 808, in __init__
    self.do_handshake()
  File "C:\Users\nayana\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 1061, in do_handshake
    self._sslobj.do_handshake()
  File "C:\Users\nayana\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 683, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\adapters.py", line 423, in send
    timeout=timeout
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\packages\urllib3\connectionpool.py", line 621, in urlopen
    raise SSLError(e)
pip._vendor.requests.packages.urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\utils\outdated.py", line 126, in pip_version_check
    headers={"Accept": "application/json"},
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\sessions.py", line 488, in get
    return self.request('GET', url, **kwargs)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\download.py", line 386, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\cachecontrol\adapter.py", line 47, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\adapters.py", line 497, in send
    raise SSLError(e, request=request)
pip._vendor.requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)

(myvenv) C:\Users\nayana\djangogirls>pip install django~=1.10.0 -vv
Config variable 'Py_DEBUG' is unset, Python ABI tag may be incorrect
Config variable 'WITH_PYMALLOC' is unset, Python ABI tag may be incorrect
Collecting django~=1.10.0
  1 location(s) to search for versions of django:
  * https://pypi.python.org/simple/django/
  Getting page https://pypi.python.org/simple/django/
  Looking up "https://pypi.python.org/simple/django/" in the cache
  No cache entry available
  Starting new HTTPS connection (1): pypi.python.org
  Could not fetch URL https://pypi.python.org/simple/django/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
  Could not find a version that satisfies the requirement django~=1.10.0 (from versions: )
Cleaning up...
No matching distribution found for django~=1.10.0
Exception information:
Traceback (most recent call last):
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\commands\install.py", line 324, in run
    requirement_set.prepare_files(finder)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\req\req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\req\req_set.py", line 554, in _prepare_file
    require_hashes
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\req\req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\index.py", line 514, in find_requirement
    'No matching distribution found for %s' % req
pip.exceptions.DistributionNotFound: No matching distribution found for django~=1.10.0
Looking up "https://pypi.python.org/pypi/pip/json" in the cache
No cache entry available
Starting new HTTPS connection (1): pypi.python.org
There was an error checking the latest version of pip
Traceback (most recent call last):
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\packages\urllib3\connectionpool.py", line 589, in urlopen
    self._prepare_proxy(conn)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\packages\urllib3\connectionpool.py", line 797, in _prepare_proxy
    conn.connect()
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\packages\urllib3\connection.py", line 289, in connect
    ssl_version=resolved_ssl_version)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\packages\urllib3\util\ssl_.py", line 308, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Users\nayana\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 401, in wrap_socket
    _context=self, _session=session)
  File "C:\Users\nayana\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 808, in __init__
    self.do_handshake()
  File "C:\Users\nayana\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 1061, in do_handshake
    self._sslobj.do_handshake()
  File "C:\Users\nayana\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 683, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\adapters.py", line 423, in send
    timeout=timeout
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\packages\urllib3\connectionpool.py", line 621, in urlopen
    raise SSLError(e)
pip._vendor.requests.packages.urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\utils\outdated.py", line 126, in pip_version_check
    headers={"Accept": "application/json"},
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\sessions.py", line 488, in get
    return self.request('GET', url, **kwargs)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\download.py", line 386, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\cachecontrol\adapter.py", line 47, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\adapters.py", line 497, in send
    raise SSLError(e, request=request)
pip._vendor.requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)

(myvenv) C:\Users\nayana\djangogirls>pip install django~=1.10.0
Collecting django~=1.10.0
  Could not fetch URL https://pypi.python.org/simple/django/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
  Could not find a version that satisfies the requirement django~=1.10.0 (from versions: )
No matching distribution found for django~=1.10.0

(myvenv) C:\Users\nayana\djangogirls>pip install django==1.10 -vv
Config variable 'Py_DEBUG' is unset, Python ABI tag may be incorrect
Config variable 'WITH_PYMALLOC' is unset, Python ABI tag may be incorrect
Collecting django==1.10
  1 location(s) to search for versions of django:
  * https://pypi.python.org/simple/django/
  Getting page https://pypi.python.org/simple/django/
  Looking up "https://pypi.python.org/simple/django/" in the cache
  No cache entry available
  Starting new HTTPS connection (1): pypi.python.org
  Could not fetch URL https://pypi.python.org/simple/django/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
  Could not find a version that satisfies the requirement django==1.10 (from versions: )
Cleaning up...
No matching distribution found for django==1.10
Exception information:
Traceback (most recent call last):
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\commands\install.py", line 324, in run
    requirement_set.prepare_files(finder)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\req\req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\req\req_set.py", line 554, in _prepare_file
    require_hashes
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\req\req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\index.py", line 514, in find_requirement
    'No matching distribution found for %s' % req
pip.exceptions.DistributionNotFound: No matching distribution found for django==1.10
Looking up "https://pypi.python.org/pypi/pip/json" in the cache
No cache entry available
Starting new HTTPS connection (1): pypi.python.org
There was an error checking the latest version of pip
Traceback (most recent call last):
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\packages\urllib3\connectionpool.py", line 589, in urlopen
    self._prepare_proxy(conn)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\packages\urllib3\connectionpool.py", line 797, in _prepare_proxy
    conn.connect()
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\packages\urllib3\connection.py", line 289, in connect
    ssl_version=resolved_ssl_version)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\packages\urllib3\util\ssl_.py", line 308, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Users\nayana\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 401, in wrap_socket
    _context=self, _session=session)
  File "C:\Users\nayana\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 808, in __init__
    self.do_handshake()
  File "C:\Users\nayana\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 1061, in do_handshake
    self._sslobj.do_handshake()
  File "C:\Users\nayana\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 683, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\adapters.py", line 423, in send
    timeout=timeout
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\packages\urllib3\connectionpool.py", line 621, in urlopen
    raise SSLError(e)
pip._vendor.requests.packages.urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\utils\outdated.py", line 126, in pip_version_check
    headers={"Accept": "application/json"},
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\sessions.py", line 488, in get
    return self.request('GET', url, **kwargs)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\download.py", line 386, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\cachecontrol\adapter.py", line 47, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\adapters.py", line 497, in send
    raise SSLError(e, request=request)
pip._vendor.requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)

(myvenv) C:\Users\nayana\djangogirls>pip install --upgraded pip

Usage:
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

no such option: --upgraded

(myvenv) C:\Users\nayana\djangogirls>pip install --upgrade pip
Could not fetch URL https://pypi.python.org/simple/pip/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
Requirement already up-to-date: pip in c:\users\nayana\djangogirls\myvenv\lib\site-packages

(myvenv) C:\Users\nayana\djangogirls>pip install django==1.10 -vv
Config variable 'Py_DEBUG' is unset, Python ABI tag may be incorrect
Config variable 'WITH_PYMALLOC' is unset, Python ABI tag may be incorrect
Collecting django==1.10
  1 location(s) to search for versions of django:
  * https://pypi.python.org/simple/django/
  Getting page https://pypi.python.org/simple/django/
  Looking up "https://pypi.python.org/simple/django/" in the cache
  No cache entry available
  Starting new HTTPS connection (1): pypi.python.org
  Could not fetch URL https://pypi.python.org/simple/django/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
  Could not find a version that satisfies the requirement django==1.10 (from versions: )
Cleaning up...
No matching distribution found for django==1.10
Exception information:
Traceback (most recent call last):
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\commands\install.py", line 324, in run
    requirement_set.prepare_files(finder)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\req\req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\req\req_set.py", line 554, in _prepare_file
    require_hashes
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\req\req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\index.py", line 514, in find_requirement
    'No matching distribution found for %s' % req
pip.exceptions.DistributionNotFound: No matching distribution found for django==1.10
Looking up "https://pypi.python.org/pypi/pip/json" in the cache
No cache entry available
Starting new HTTPS connection (1): pypi.python.org
There was an error checking the latest version of pip
Traceback (most recent call last):
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\packages\urllib3\connectionpool.py", line 589, in urlopen
    self._prepare_proxy(conn)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\packages\urllib3\connectionpool.py", line 797, in _prepare_proxy
    conn.connect()
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\packages\urllib3\connection.py", line 289, in connect
    ssl_version=resolved_ssl_version)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\packages\urllib3\util\ssl_.py", line 308, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Users\nayana\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 401, in wrap_socket
    _context=self, _session=session)
  File "C:\Users\nayana\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 808, in __init__
    self.do_handshake()
  File "C:\Users\nayana\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 1061, in do_handshake
    self._sslobj.do_handshake()
  File "C:\Users\nayana\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 683, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\adapters.py", line 423, in send
    timeout=timeout
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\packages\urllib3\connectionpool.py", line 621, in urlopen
    raise SSLError(e)
pip._vendor.requests.packages.urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\utils\outdated.py", line 126, in pip_version_check
    headers={"Accept": "application/json"},
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\sessions.py", line 488, in get
    return self.request('GET', url, **kwargs)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\download.py", line 386, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\cachecontrol\adapter.py", line 47, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\adapters.py", line 497, in send
    raise SSLError(e, request=request)
pip._vendor.requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)

(myvenv) C:\Users\nayana\djangogirls>pip install --upgrade urllib3
Collecting urllib3
  Could not fetch URL https://pypi.python.org/simple/urllib3/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
  Could not find a version that satisfies the requirement urllib3 (from versions: )
No matching distribution found for urllib3

(myvenv) C:\Users\nayana\djangogirls>pip --version
pip 9.0.1 from c:\users\nayana\djangogirls\myvenv\lib\site-packages (python 3.6)

(myvenv) C:\Users\nayana\djangogirls>pip install --trusterd-host=pypi.python --upgrade pip

Usage:
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

no such option: --trusterd-host

(myvenv) C:\Users\nayana\djangogirls>pip install --trusted-host=pypi.python --upgrade pip
Could not fetch URL https://pypi.python.org/simple/pip/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
Requirement already up-to-date: pip in c:\users\nayana\djangogirls\myvenv\lib\site-packages

(myvenv) C:\Users\nayana\djangogirls>pip install --trusted-host=pypi.python.org --upgrade pip
Requirement already up-to-date: pip in c:\users\nayana\djangogirls\myvenv\lib\site-packages

(myvenv) C:\Users\nayana\djangogirls>pip install --trusted-host=pypi.python.org django==1.10
Collecting django==1.10
  Downloading Django-1.10-py2.py3-none-any.whl
     \ 17.8MB 1.4MB/s
Installing collected packages: django
Successfully installed django-1.10

(myvenv) C:\Users\nayana\djangogirls>
(myvenv) C:\Users\nayana\djangogirls>
(myvenv) C:\Users\nayana\djangogirls>whoami
desktop-tk50ank\nayana

(myvenv) C:\Users\nayana\djangogirls>python
Python 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> 2+3
5
>>> 2**3
8
>>> "nayana"
'nayana'
>>> "nayana"+"l"
'nayanal'
>>> "nayana"*3
'nayananayananayana'
>>> "nayana".upper()
'NAYANA'
>>> len("nayana")
6
>>> len(str(446))
3
>>> name="nayana"
>>> name
'nayana'
>>> len(name)
6
>>> print(name)
nayana
>>> name
'nayana'
>>> []
[]
>>> sweets=[2 , 6 7]
  File "<stdin>", line 1
    sweets=[2 , 6 7]
                  ^
SyntaxError: invalid syntax
>>> sweets=[2 , 6, 7]
>>> sweets.sort()
>>> print(sweets)
[2, 6, 7]
>>> sweets.reverse9)
  File "<stdin>", line 1
    sweets.reverse9)
                   ^
SyntaxError: invalid syntax
>>> sweets.reverse()
>>> print(sweets)
[7, 6, 2]
>>> sweets.append()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: append() takes exactly one argument (0 given)
>>> sweets.append(25)
>>> print(sweets)
[7, 6, 2, 25]
>>> sweets.pop(2)
2
>>> print(sweets)
[7, 6, 25]
>>> student={'name:'nayana','place':'kerala'}
  File "<stdin>", line 1
    student={'name:'nayana','place':'kerala'}
                         ^
SyntaxError: invalid syntax
>>> student={'name':'nayana','place':'kerala'}
>>> print(student['name'])
nayana
>>> student['lang']=python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'python' is not defined
>>> student['lang']='python'
>>> student
{'name': 'nayana', 'place': 'kerala', 'lang': 'python'}
>>> len(student)
3
>>> student.pop(place)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'place' is not defined
>>> student.pop('place')
'kerala'
>>> student
{'name': 'nayana', 'lang': 'python'}
>>> 6>=12/2
True
>>> apple and orange
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'apple' is not defined
>>> True and True
True
>>> True and False
False
>>> exit()

(myvenv) C:\Users\nayana\djangogirls>cd C:\Users\nayana\Desktop

(myvenv) C:\Users\nayana\Desktop>python3 new.py
'python3' is not recognized as an internal or external command,
operable program or batch file.

(myvenv) C:\Users\nayana\Desktop>python3 new.py
'python3' is not recognized as an internal or external command,
operable program or batch file.

(myvenv) C:\Users\nayana\Desktop>python new.py
hello

(myvenv) C:\Users\nayana\Desktop>python
Python 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()

(myvenv) C:\Users\nayana\Desktop>python new.py
It works!

(myvenv) C:\Users\nayana\Desktop>python new.py
Hey Sonja!

(myvenv) C:\Users\nayana\Desktop>python new.py
  File "new.py", line 2
    print(hi)
        ^
IndentationError: expected an indented block

(myvenv) C:\Users\nayana\Desktop>python new.py
  File "new.py", line 2
    print(hi)
        ^
IndentationError: expected an indented block

(myvenv) C:\Users\nayana\Desktop>python new.py
  File "new.py", line 2
    print('hi')
        ^
IndentationError: expected an indented block

(myvenv) C:\Users\nayana\Desktop>python new.py
hi
helo

(myvenv) C:\Users\nayana\Desktop>python new.py
hi
helo

(myvenv) C:\Users\nayana\Desktop>python new.py
Traceback (most recent call last):
  File "new.py", line 6, in <module>
    hi()
TypeError: hi() missing 1 required positional argument: 'name'

(myvenv) C:\Users\nayana\Desktop>python new.py
Traceback (most recent call last):
  File "new.py", line 8, in <module>
    hi()
TypeError: hi() missing 1 required positional argument: 'name'

(myvenv) C:\Users\nayana\Desktop>python new.py
Traceback (most recent call last):
  File "new.py", line 8, in <module>
    hi()
TypeError: hi() missing 1 required positional argument: 'nayana'

(myvenv) C:\Users\nayana\Desktop>python new.py
Traceback (most recent call last):
  File "new.py", line 8, in <module>
    hi(nayana)
NameError: name 'nayana' is not defined

(myvenv) C:\Users\nayana\Desktop>python new.py
hi

(myvenv) C:\Users\nayana\Desktop>python new.py
  File "new.py", line 2
    print("hi"+name+"!")
        ^
IndentationError: expected an indented block

(myvenv) C:\Users\nayana\Desktop>python new.py
Traceback (most recent call last):
  File "new.py", line 4, in <module>
    hi(nayana)
NameError: name 'nayana' is not defined

(myvenv) C:\Users\nayana\Desktop>python new.py
hinayana!

(myvenv) C:\Users\nayana\Desktop>python new.py
hinayana!
next gal

(myvenv) C:\Users\nayana\Desktop>python new.py
  File "new.py", line 7
    for name in girls
                    ^
SyntaxError: invalid syntax

(myvenv) C:\Users\nayana\Desktop>python new.py
hinayana!
next gal
hinayana!
next gal
hinayana!
next gal

(myvenv) C:\Users\nayana\Desktop>python new.py
  File "new.py", line 1
    for i in range(1,6)
                      ^
SyntaxError: invalid syntax

(myvenv) C:\Users\nayana\Desktop>python new.py
1
2
3
4
5

(myvenv) C:\Users\nayana\Desktop>djngo-admin.py startproject mysite .
'djngo-admin.py' is not recognized as an internal or external command,
operable program or batch file.

(myvenv) C:\Users\nayana\Desktop>django-admin.py startproject mysite .

(myvenv) C:\Users\nayana\Desktop>mysite/setting.py
'mysite' is not recognized as an internal or external command,
operable program or batch file.

(myvenv) C:\Users\nayana\Desktop>django-admin.py startproject mysite .
CommandError: C:\Users\nayana\Desktop\manage.py already exists, overlaying a project or app into an existing directory won't replace conflicting files

(myvenv) C:\Users\nayana\Desktop>django-admin.py startproject mysite .
CommandError: C:\Users\nayana\Desktop\manage.py already exists, overlaying a project or app into an existing directory won't replace conflicting files

(myvenv) C:\Users\nayana\Desktop>django-admin.py startproject mysite .
CommandError: C:\Users\nayana\Desktop\manage.py already exists, overlaying a project or app into an existing directory won't replace conflicting files

(myvenv) C:\Users\nayana\Desktop>mysite/setting.py
'mysite' is not recognized as an internal or external command,
operable program or batch file.

(myvenv) C:\Users\nayana\Desktop>django-admin.py startproject mysite .

(myvenv) C:\Users\nayana\Desktop>dir
 Volume in drive C is OS
 Volume Serial Number is D6BD-931E

 Directory of C:\Users\nayana\Desktop

22-Jan-17  12:29 PM    <DIR>          .
22-Jan-17  12:29 PM    <DIR>          ..
22-Jan-17  08:49 AM             2,288 Atom.lnk
19-Jan-17  01:18 AM       104,284,200 AtomSetup.exe
22-Jan-17  09:09 AM               772 Desktop - Shortcut.lnk
20-Jan-17  12:49 PM       742,558,197 dhangal.mkv
22-Jan-17  12:28 PM    <DIR>          django
23-Jul-16  07:10 PM             1,106 KMPlayer.lnk
22-Jan-17  12:29 PM               804 manage.py
22-Jan-17  12:29 PM    <DIR>          mysite
22-Jan-17  12:16 PM                34 new.py
18-Jan-17  10:22 PM        31,505,640 python-3.6.0-amd64.exe
13-Dec-16  07:44 PM           105,922 resume1.pdf
23-Jul-16  06:57 PM             1,224 Youtube Downloader HD.lnk
              10 File(s)    878,460,187 bytes
               4 Dir(s)  183,955,378,176 bytes free

(myvenv) C:\Users\nayana\Desktop>python manage.py migrate
python: can't open file 'manage.py': [Errno 2] No such file or directory

(myvenv) C:\Users\nayana\Desktop>dir
 Volume in drive C is OS
 Volume Serial Number is D6BD-931E

 Directory of C:\Users\nayana\Desktop

22-Jan-17  12:30 PM    <DIR>          .
22-Jan-17  12:30 PM    <DIR>          ..
22-Jan-17  08:49 AM             2,288 Atom.lnk
19-Jan-17  01:18 AM       104,284,200 AtomSetup.exe
22-Jan-17  09:09 AM               772 Desktop - Shortcut.lnk
20-Jan-17  12:49 PM       742,558,197 dhangal.mkv
22-Jan-17  12:28 PM    <DIR>          django
23-Jul-16  07:10 PM             1,106 KMPlayer.lnk
22-Jan-17  12:16 PM                34 new.py
18-Jan-17  10:22 PM        31,505,640 python-3.6.0-amd64.exe
13-Dec-16  07:44 PM           105,922 resume1.pdf
23-Jul-16  06:57 PM             1,224 Youtube Downloader HD.lnk
               9 File(s)    878,459,383 bytes
               3 Dir(s)  184,097,792,000 bytes free

(myvenv) C:\Users\nayana\Desktop>cd django

(myvenv) C:\Users\nayana\Desktop\django>dir
 Volume in drive C is OS
 Volume Serial Number is D6BD-931E

 Directory of C:\Users\nayana\Desktop\django

22-Jan-17  12:28 PM    <DIR>          .
22-Jan-17  12:28 PM    <DIR>          ..
22-Jan-17  12:23 PM               804 manage.py
22-Jan-17  12:23 PM    <DIR>          mysite
               1 File(s)            804 bytes
               3 Dir(s)  184,097,787,904 bytes free

(myvenv) C:\Users\nayana\Desktop\django>python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, sessions
Running migrations:
  Rendering model states... DONE
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying sessions.0001_initial... OK

(myvenv) C:\Users\nayana\Desktop\django>python manage.py runserver
Performing system checks...

System check identified no issues (0 silenced).
January 22, 2017 - 12:49:20
Django version 1.10, using settings 'mysite.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
[22/Jan/2017 12:52:59] "GET / HTTP/1.1" 200 1767
Not Found: /favicon.ico
[22/Jan/2017 12:52:59] "GET /favicon.ico HTTP/1.1" 404 1936
Not Found: /favicon.ico
[22/Jan/2017 12:52:59] "GET /favicon.ico HTTP/1.1" 404 1936

















































































































































































































C:\Users\nayana>mkdirdjangogirls
'mkdirdjangogirls' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\nayana>mkdir djangogirls

C:\Users\nayana>cd djangogirls

C:\Users\nayana\djangogirls> C:\Users\nayana\AppData\Local\Programs\Python\Python36\python -m venv myvenv

C:\Users\nayana\djangogirls>myvenv\Scripts\activate
(myvenv) C:\Users\nayana\djangogirls>pip install --upgrade pip
Could not fetch URL https://pypi.python.org/simple/pip/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
Requirement already up-to-date: pip in c:\users\nayana\djangogirls\myvenv\lib\site-packages

(myvenv) C:\Users\nayana\djangogirls>pip install django~=1.10.0
Collecting django~=1.10.0
  Could not fetch URL https://pypi.python.org/simple/django/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
  Could not find a version that satisfies the requirement django~=1.10.0 (from versions: )
No matching distribution found for django~=1.10.0

(myvenv) C:\Users\nayana\djangogirls>pip install --upgrade pip
Could not fetch URL https://pypi.python.org/simple/pip/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
Requirement already up-to-date: pip in c:\users\nayana\djangogirls\myvenv\lib\site-packages

(myvenv) C:\Users\nayana\djangogirls>pip install
You must give at least one requirement to install (see "pip help install")

(myvenv) C:\Users\nayana\djangogirls>pip install --upgrade pip
Could not fetch URL https://pypi.python.org/simple/pip/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
Requirement already up-to-date: pip in c:\users\nayana\djangogirls\myvenv\lib\site-packages

(myvenv) C:\Users\nayana\djangogirls>pip install --upgrade pip
Could not fetch URL https://pypi.python.org/simple/pip/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
Requirement already up-to-date: pip in c:\users\nayana\djangogirls\myvenv\lib\site-packages

(myvenv) C:\Users\nayana\djangogirls>pip install django~=1.10.0
Collecting django~=1.10.0
  Could not fetch URL https://pypi.python.org/simple/django/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
  Could not find a version that satisfies the requirement django~=1.10.0 (from versions: )
No matching distribution found for django~=1.10.0

(myvenv) C:\Users\nayana\djangogirls>pip install django~=1.10.0
Collecting django~=1.10.0
  Could not fetch URL https://pypi.python.org/simple/django/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
  Could not find a version that satisfies the requirement django~=1.10.0 (from versions: )
No matching distribution found for django~=1.10.0

(myvenv) C:\Users\nayana\djangogirls>pip install --upgrade pip
Could not fetch URL https://pypi.python.org/simple/pip/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
Requirement already up-to-date: pip in c:\users\nayana\djangogirls\myvenv\lib\site-packages

(myvenv) C:\Users\nayana\djangogirls>python -m pip install django~=1.10.0
Collecting django~=1.10.0
  Could not fetch URL https://pypi.python.org/simple/django/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
  Could not find a version that satisfies the requirement django~=1.10.0 (from versions: )
No matching distribution found for django~=1.10.0

(myvenv) C:\Users\nayana\djangogirls>python -m pip install django~=1.10.0
Collecting django~=1.10.0
  Could not fetch URL https://pypi.python.org/simple/django/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
  Could not find a version that satisfies the requirement django~=1.10.0 (from versions: )
No matching distribution found for django~=1.10.0

(myvenv) C:\Users\nayana\djangogirls>python -m pip install django~=1.10.0
Collecting django~=1.10.0
  Could not fetch URL https://pypi.python.org/simple/django/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
  Could not find a version that satisfies the requirement django~=1.10.0 (from versions: )
No matching distribution found for django~=1.10.0

(myvenv) C:\Users\nayana\djangogirls>python -m pip install django~=1.10.0
Collecting django~=1.10.0
  Could not fetch URL https://pypi.python.org/simple/django/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
  Could not find a version that satisfies the requirement django~=1.10.0 (from versions: )
No matching distribution found for django~=1.10.0

(myvenv) C:\Users\nayana\djangogirls>python -m pip install django~=1.10.0
Collecting django~=1.10.0
  Could not fetch URL https://pypi.python.org/simple/django/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
  Could not find a version that satisfies the requirement django~=1.10.0 (from versions: )
No matching distribution found for django~=1.10.0

(myvenv) C:\Users\nayana\djangogirls>pip install --upgrade pip
Could not fetch URL https://pypi.python.org/simple/pip/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
Requirement already up-to-date: pip in c:\users\nayana\djangogirls\myvenv\lib\site-packages

(myvenv) C:\Users\nayana\djangogirls>python
Python 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()

(myvenv) C:\Users\nayana\djangogirls>python -m pip install django~=1.10.1
Collecting django~=1.10.1
  Could not fetch URL https://pypi.python.org/simple/django/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
  Could not find a version that satisfies the requirement django~=1.10.1 (from versions: )
No matching distribution found for django~=1.10.1

(myvenv) C:\Users\nayana\djangogirls>pip install django~=1.
Invalid requirement: 'django~=1.'
Traceback (most recent call last):
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\packaging\requirements.py", line 92, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\pyparsing.py", line 1617, in parseString
    raise exc
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\pyparsing.py", line 1607, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\pyparsing.py", line 3376, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\pyparsing.py", line 1383, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\pyparsing.py", line 3164, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pip._vendor.pyparsing.ParseException: Expected stringEnd (at char 6), (line:1, col:7)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\req\req_install.py", line 82, in __init__
    req = Requirement(req)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\packaging\requirements.py", line 96, in __init__
    requirement_string[e.loc:e.loc + 8]))
pip._vendor.packaging.requirements.InvalidRequirement: Invalid requirement, parse error at "'~=1.'"


(myvenv) C:\Users\nayana\djangogirls>pip install django~=1.10.1
Collecting django~=1.10.1
  Could not fetch URL https://pypi.python.org/simple/django/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
  Could not find a version that satisfies the requirement django~=1.10.1 (from versions: )
No matching distribution found for django~=1.10.1

(myvenv) C:\Users\nayana\djangogirls>pip install django~=1.10.0
Collecting django~=1.10.0
  Could not fetch URL https://pypi.python.org/simple/django/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
  Could not find a version that satisfies the requirement django~=1.10.0 (from versions: )
No matching distribution found for django~=1.10.0

(myvenv) C:\Users\nayana\djangogirls>pip install django==1.10.0
Collecting django==1.10.0
  Could not fetch URL https://pypi.python.org/simple/django/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
  Could not find a version that satisfies the requirement django==1.10.0 (from versions: )
No matching distribution found for django==1.10.0

(myvenv) C:\Users\nayana\djangogirls>pip3 install django~=1.10.0
Collecting django~=1.10.0
  Could not fetch URL https://pypi.python.org/simple/django/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
  Could not find a version that satisfies the requirement django~=1.10.0 (from versions: )
No matching distribution found for django~=1.10.0

(myvenv) C:\Users\nayana\djangogirls>pip3 install django~=1.10.0
Collecting django~=1.10.0
  Could not fetch URL https://pypi.python.org/simple/django/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
  Could not find a version that satisfies the requirement django~=1.10.0 (from versions: )
No matching distribution found for django~=1.10.0

(myvenv) C:\Users\nayana\djangogirls>pip install django==1.10.0
Collecting django==1.10.0
  Could not fetch URL https://pypi.python.org/simple/django/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
  Could not find a version that satisfies the requirement django==1.10.0 (from versions: )
No matching distribution found for django==1.10.0

(myvenv) C:\Users\nayana\djangogirls>pip install Django~=1.10.0
Collecting Django~=1.10.0
  Could not fetch URL https://pypi.python.org/simple/django/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
  Could not find a version that satisfies the requirement Django~=1.10.0 (from versions: )
No matching distribution found for Django~=1.10.0

(myvenv) C:\Users\nayana\djangogirls>pip install Django==1.10.0
Collecting Django==1.10.0
  Could not fetch URL https://pypi.python.org/simple/django/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
  Could not find a version that satisfies the requirement Django==1.10.0 (from versions: )
No matching distribution found for Django==1.10.0

(myvenv) C:\Users\nayana\djangogirls>pip install Django
Collecting Django
  Could not fetch URL https://pypi.python.org/simple/django/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
  Could not find a version that satisfies the requirement Django (from versions: )
No matching distribution found for Django

(myvenv) C:\Users\nayana\djangogirls>pip install django
Collecting django
  Could not fetch URL https://pypi.python.org/simple/django/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
  Could not find a version that satisfies the requirement django (from versions: )
No matching distribution found for django

(myvenv) C:\Users\nayana\djangogirls>ping google.com

Pinging google.com [172.217.26.174] with 32 bytes of data:
Reply from 172.217.26.174: bytes=32 time=73ms TTL=56
Reply from 172.217.26.174: bytes=32 time=69ms TTL=56
Reply from 172.217.26.174: bytes=32 time=69ms TTL=56

Ping statistics for 172.217.26.174:
    Packets: Sent = 3, Received = 3, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 69ms, Maximum = 73ms, Average = 70ms
Control-C
^C
(myvenv) C:\Users\nayana\djangogirls>python3
'python3' is not recognized as an internal or external command,
operable program or batch file.

(myvenv) C:\Users\nayana\djangogirls>python
Python 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()

(myvenv) C:\Users\nayana\djangogirls>pip install --upgrade pip
Could not fetch URL https://pypi.python.org/simple/pip/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
Requirement already up-to-date: pip in c:\users\nayana\djangogirls\myvenv\lib\site-packages

(myvenv) C:\Users\nayana\djangogirls>easy_install pip
Searching for pip
Best match: pip 9.0.1
Adding pip 9.0.1 to easy-install.pth file
Installing pip-script.py script to c:\users\nayana\djangogirls\myvenv\Scripts
Installing pip.exe script to c:\users\nayana\djangogirls\myvenv\Scripts
Installing pip3-script.py script to c:\users\nayana\djangogirls\myvenv\Scripts
Installing pip3.exe script to c:\users\nayana\djangogirls\myvenv\Scripts
Installing pip3.5-script.py script to c:\users\nayana\djangogirls\myvenv\Scripts
Installing pip3.5.exe script to c:\users\nayana\djangogirls\myvenv\Scripts

Using c:\users\nayana\djangogirls\myvenv\lib\site-packages
Processing dependencies for pip
Finished processing dependencies for pip

(myvenv) C:\Users\nayana\djangogirls>pip install Django==1.10.0
Collecting Django==1.10.0
  Could not fetch URL https://pypi.python.org/simple/django/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
  Could not find a version that satisfies the requirement Django==1.10.0 (from versions: )
No matching distribution found for Django==1.10.0

(myvenv) C:\Users\nayana\djangogirls>pip --version
pip 9.0.1 from c:\users\nayana\djangogirls\myvenv\lib\site-packages (python 3.6)

(myvenv) C:\Users\nayana\djangogirls>pip --version
Traceback (most recent call last):
  File "C:\Users\nayana\djangogirls\myvenv\Scripts\pip-script.py", line 6, in <module>
    from pkg_resources import load_entry_point
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pkg_resources\__init__.py", line 36, in <module>
    import email.parser
  File "C:\Users\nayana\AppData\Local\Programs\Python\Python36\lib\email\parser.py", line 12, in <module>
    from email.feedparser import FeedParser, BytesFeedParser
  File "C:\Users\nayana\AppData\Local\Programs\Python\Python36\lib\email\feedparser.py", line 27, in <module>
    from email._policybase import compat32
  File "C:\Users\nayana\AppData\Local\Programs\Python\Python36\lib\email\_policybase.py", line 9, in <module>
    from email.utils import _has_surrogates
  File "C:\Users\nayana\AppData\Local\Programs\Python\Python36\lib\email\utils.py", line 28, in <module>
    import random
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 764, in get_code
  File "<frozen importlib._bootstrap_external>", line 832, in get_data
KeyboardInterrupt

(myvenv) C:\Users\nayana\djangogirls>pip install Django==1.10.0
Collecting Django==1.10.0
  Could not fetch URL https://pypi.python.org/simple/django/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
  Could not find a version that satisfies the requirement Django==1.10.0 (from versions: )
No matching distribution found for Django==1.10.0

(myvenv) C:\Users\nayana\djangogirls>pip install -upgrade pip.

Usage:
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

no such option: -u

(myvenv) C:\Users\nayana\djangogirls>pip install --upgrade pip
Could not fetch URL https://pypi.python.org/simple/pip/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
Requirement already up-to-date: pip in c:\users\nayana\djangogirls\myvenv\lib\site-packages

(myvenv) C:\Users\nayana\djangogirls>pip install django~=1.10.0
Collecting django~=1.10.0
  Could not fetch URL https://pypi.python.org/simple/django/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
  Could not find a version that satisfies the requirement django~=1.10.0 (from versions: )
No matching distribution found for django~=1.10.0

(myvenv) C:\Users\nayana\djangogirls>pip install django~=1.10.0 -vv
Config variable 'Py_DEBUG' is unset, Python ABI tag may be incorrect
Config variable 'WITH_PYMALLOC' is unset, Python ABI tag may be incorrect
Collecting django~=1.10.0
  1 location(s) to search for versions of django:
  * https://pypi.python.org/simple/django/
  Getting page https://pypi.python.org/simple/django/
  Looking up "https://pypi.python.org/simple/django/" in the cache
  No cache entry available
  Starting new HTTPS connection (1): pypi.python.org
  Could not fetch URL https://pypi.python.org/simple/django/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
  Could not find a version that satisfies the requirement django~=1.10.0 (from versions: )
Cleaning up...
No matching distribution found for django~=1.10.0
Exception information:
Traceback (most recent call last):
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\commands\install.py", line 324, in run
    requirement_set.prepare_files(finder)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\req\req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\req\req_set.py", line 554, in _prepare_file
    require_hashes
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\req\req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\index.py", line 514, in find_requirement
    'No matching distribution found for %s' % req
pip.exceptions.DistributionNotFound: No matching distribution found for django~=1.10.0
Looking up "https://pypi.python.org/pypi/pip/json" in the cache
No cache entry available
Starting new HTTPS connection (1): pypi.python.org
There was an error checking the latest version of pip
Traceback (most recent call last):
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\packages\urllib3\connectionpool.py", line 589, in urlopen
    self._prepare_proxy(conn)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\packages\urllib3\connectionpool.py", line 797, in _prepare_proxy
    conn.connect()
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\packages\urllib3\connection.py", line 289, in connect
    ssl_version=resolved_ssl_version)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\packages\urllib3\util\ssl_.py", line 308, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Users\nayana\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 401, in wrap_socket
    _context=self, _session=session)
  File "C:\Users\nayana\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 808, in __init__
    self.do_handshake()
  File "C:\Users\nayana\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 1061, in do_handshake
    self._sslobj.do_handshake()
  File "C:\Users\nayana\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 683, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\adapters.py", line 423, in send
    timeout=timeout
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\packages\urllib3\connectionpool.py", line 621, in urlopen
    raise SSLError(e)
pip._vendor.requests.packages.urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\utils\outdated.py", line 126, in pip_version_check
    headers={"Accept": "application/json"},
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\sessions.py", line 488, in get
    return self.request('GET', url, **kwargs)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\download.py", line 386, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\cachecontrol\adapter.py", line 47, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\adapters.py", line 497, in send
    raise SSLError(e, request=request)
pip._vendor.requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)

(myvenv) C:\Users\nayana\djangogirls>pip install django~=1.10.0 -vv
Config variable 'Py_DEBUG' is unset, Python ABI tag may be incorrect
Config variable 'WITH_PYMALLOC' is unset, Python ABI tag may be incorrect
Collecting django~=1.10.0
  1 location(s) to search for versions of django:
  * https://pypi.python.org/simple/django/
  Getting page https://pypi.python.org/simple/django/
  Looking up "https://pypi.python.org/simple/django/" in the cache
  No cache entry available
  Starting new HTTPS connection (1): pypi.python.org
  Could not fetch URL https://pypi.python.org/simple/django/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
  Could not find a version that satisfies the requirement django~=1.10.0 (from versions: )
Cleaning up...
No matching distribution found for django~=1.10.0
Exception information:
Traceback (most recent call last):
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\commands\install.py", line 324, in run
    requirement_set.prepare_files(finder)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\req\req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\req\req_set.py", line 554, in _prepare_file
    require_hashes
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\req\req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\index.py", line 514, in find_requirement
    'No matching distribution found for %s' % req
pip.exceptions.DistributionNotFound: No matching distribution found for django~=1.10.0
Looking up "https://pypi.python.org/pypi/pip/json" in the cache
No cache entry available
Starting new HTTPS connection (1): pypi.python.org
There was an error checking the latest version of pip
Traceback (most recent call last):
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\packages\urllib3\connectionpool.py", line 589, in urlopen
    self._prepare_proxy(conn)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\packages\urllib3\connectionpool.py", line 797, in _prepare_proxy
    conn.connect()
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\packages\urllib3\connection.py", line 289, in connect
    ssl_version=resolved_ssl_version)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\packages\urllib3\util\ssl_.py", line 308, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Users\nayana\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 401, in wrap_socket
    _context=self, _session=session)
  File "C:\Users\nayana\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 808, in __init__
    self.do_handshake()
  File "C:\Users\nayana\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 1061, in do_handshake
    self._sslobj.do_handshake()
  File "C:\Users\nayana\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 683, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\adapters.py", line 423, in send
    timeout=timeout
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\packages\urllib3\connectionpool.py", line 621, in urlopen
    raise SSLError(e)
pip._vendor.requests.packages.urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\utils\outdated.py", line 126, in pip_version_check
    headers={"Accept": "application/json"},
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\sessions.py", line 488, in get
    return self.request('GET', url, **kwargs)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\download.py", line 386, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\cachecontrol\adapter.py", line 47, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\adapters.py", line 497, in send
    raise SSLError(e, request=request)
pip._vendor.requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)

(myvenv) C:\Users\nayana\djangogirls>pip install django~=1.10.0 -vv
Config variable 'Py_DEBUG' is unset, Python ABI tag may be incorrect
Config variable 'WITH_PYMALLOC' is unset, Python ABI tag may be incorrect
Collecting django~=1.10.0
  1 location(s) to search for versions of django:
  * https://pypi.python.org/simple/django/
  Getting page https://pypi.python.org/simple/django/
  Looking up "https://pypi.python.org/simple/django/" in the cache
  No cache entry available
  Starting new HTTPS connection (1): pypi.python.org
  Could not fetch URL https://pypi.python.org/simple/django/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
  Could not find a version that satisfies the requirement django~=1.10.0 (from versions: )
Cleaning up...
No matching distribution found for django~=1.10.0
Exception information:
Traceback (most recent call last):
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\commands\install.py", line 324, in run
    requirement_set.prepare_files(finder)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\req\req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\req\req_set.py", line 554, in _prepare_file
    require_hashes
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\req\req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\index.py", line 514, in find_requirement
    'No matching distribution found for %s' % req
pip.exceptions.DistributionNotFound: No matching distribution found for django~=1.10.0
Looking up "https://pypi.python.org/pypi/pip/json" in the cache
No cache entry available
Starting new HTTPS connection (1): pypi.python.org
There was an error checking the latest version of pip
Traceback (most recent call last):
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\packages\urllib3\connectionpool.py", line 589, in urlopen
    self._prepare_proxy(conn)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\packages\urllib3\connectionpool.py", line 797, in _prepare_proxy
    conn.connect()
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\packages\urllib3\connection.py", line 289, in connect
    ssl_version=resolved_ssl_version)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\packages\urllib3\util\ssl_.py", line 308, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Users\nayana\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 401, in wrap_socket
    _context=self, _session=session)
  File "C:\Users\nayana\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 808, in __init__
    self.do_handshake()
  File "C:\Users\nayana\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 1061, in do_handshake
    self._sslobj.do_handshake()
  File "C:\Users\nayana\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 683, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\adapters.py", line 423, in send
    timeout=timeout
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\packages\urllib3\connectionpool.py", line 621, in urlopen
    raise SSLError(e)
pip._vendor.requests.packages.urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\utils\outdated.py", line 126, in pip_version_check
    headers={"Accept": "application/json"},
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\sessions.py", line 488, in get
    return self.request('GET', url, **kwargs)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\download.py", line 386, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\cachecontrol\adapter.py", line 47, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\adapters.py", line 497, in send
    raise SSLError(e, request=request)
pip._vendor.requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)

(myvenv) C:\Users\nayana\djangogirls>pip install django~=1.10.0
Collecting django~=1.10.0
  Could not fetch URL https://pypi.python.org/simple/django/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
  Could not find a version that satisfies the requirement django~=1.10.0 (from versions: )
No matching distribution found for django~=1.10.0

(myvenv) C:\Users\nayana\djangogirls>pip install django==1.10 -vv
Config variable 'Py_DEBUG' is unset, Python ABI tag may be incorrect
Config variable 'WITH_PYMALLOC' is unset, Python ABI tag may be incorrect
Collecting django==1.10
  1 location(s) to search for versions of django:
  * https://pypi.python.org/simple/django/
  Getting page https://pypi.python.org/simple/django/
  Looking up "https://pypi.python.org/simple/django/" in the cache
  No cache entry available
  Starting new HTTPS connection (1): pypi.python.org
  Could not fetch URL https://pypi.python.org/simple/django/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
  Could not find a version that satisfies the requirement django==1.10 (from versions: )
Cleaning up...
No matching distribution found for django==1.10
Exception information:
Traceback (most recent call last):
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\commands\install.py", line 324, in run
    requirement_set.prepare_files(finder)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\req\req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\req\req_set.py", line 554, in _prepare_file
    require_hashes
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\req\req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\index.py", line 514, in find_requirement
    'No matching distribution found for %s' % req
pip.exceptions.DistributionNotFound: No matching distribution found for django==1.10
Looking up "https://pypi.python.org/pypi/pip/json" in the cache
No cache entry available
Starting new HTTPS connection (1): pypi.python.org
There was an error checking the latest version of pip
Traceback (most recent call last):
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\packages\urllib3\connectionpool.py", line 589, in urlopen
    self._prepare_proxy(conn)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\packages\urllib3\connectionpool.py", line 797, in _prepare_proxy
    conn.connect()
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\packages\urllib3\connection.py", line 289, in connect
    ssl_version=resolved_ssl_version)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\packages\urllib3\util\ssl_.py", line 308, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Users\nayana\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 401, in wrap_socket
    _context=self, _session=session)
  File "C:\Users\nayana\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 808, in __init__
    self.do_handshake()
  File "C:\Users\nayana\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 1061, in do_handshake
    self._sslobj.do_handshake()
  File "C:\Users\nayana\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 683, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\adapters.py", line 423, in send
    timeout=timeout
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\packages\urllib3\connectionpool.py", line 621, in urlopen
    raise SSLError(e)
pip._vendor.requests.packages.urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\utils\outdated.py", line 126, in pip_version_check
    headers={"Accept": "application/json"},
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\sessions.py", line 488, in get
    return self.request('GET', url, **kwargs)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\download.py", line 386, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\cachecontrol\adapter.py", line 47, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\adapters.py", line 497, in send
    raise SSLError(e, request=request)
pip._vendor.requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)

(myvenv) C:\Users\nayana\djangogirls>pip install --upgraded pip

Usage:
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

no such option: --upgraded

(myvenv) C:\Users\nayana\djangogirls>pip install --upgrade pip
Could not fetch URL https://pypi.python.org/simple/pip/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
Requirement already up-to-date: pip in c:\users\nayana\djangogirls\myvenv\lib\site-packages

(myvenv) C:\Users\nayana\djangogirls>pip install django==1.10 -vv
Config variable 'Py_DEBUG' is unset, Python ABI tag may be incorrect
Config variable 'WITH_PYMALLOC' is unset, Python ABI tag may be incorrect
Collecting django==1.10
  1 location(s) to search for versions of django:
  * https://pypi.python.org/simple/django/
  Getting page https://pypi.python.org/simple/django/
  Looking up "https://pypi.python.org/simple/django/" in the cache
  No cache entry available
  Starting new HTTPS connection (1): pypi.python.org
  Could not fetch URL https://pypi.python.org/simple/django/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
  Could not find a version that satisfies the requirement django==1.10 (from versions: )
Cleaning up...
No matching distribution found for django==1.10
Exception information:
Traceback (most recent call last):
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\commands\install.py", line 324, in run
    requirement_set.prepare_files(finder)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\req\req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\req\req_set.py", line 554, in _prepare_file
    require_hashes
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\req\req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\index.py", line 514, in find_requirement
    'No matching distribution found for %s' % req
pip.exceptions.DistributionNotFound: No matching distribution found for django==1.10
Looking up "https://pypi.python.org/pypi/pip/json" in the cache
No cache entry available
Starting new HTTPS connection (1): pypi.python.org
There was an error checking the latest version of pip
Traceback (most recent call last):
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\packages\urllib3\connectionpool.py", line 589, in urlopen
    self._prepare_proxy(conn)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\packages\urllib3\connectionpool.py", line 797, in _prepare_proxy
    conn.connect()
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\packages\urllib3\connection.py", line 289, in connect
    ssl_version=resolved_ssl_version)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\packages\urllib3\util\ssl_.py", line 308, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Users\nayana\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 401, in wrap_socket
    _context=self, _session=session)
  File "C:\Users\nayana\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 808, in __init__
    self.do_handshake()
  File "C:\Users\nayana\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 1061, in do_handshake
    self._sslobj.do_handshake()
  File "C:\Users\nayana\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 683, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\adapters.py", line 423, in send
    timeout=timeout
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\packages\urllib3\connectionpool.py", line 621, in urlopen
    raise SSLError(e)
pip._vendor.requests.packages.urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\utils\outdated.py", line 126, in pip_version_check
    headers={"Accept": "application/json"},
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\sessions.py", line 488, in get
    return self.request('GET', url, **kwargs)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\download.py", line 386, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\cachecontrol\adapter.py", line 47, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\adapters.py", line 497, in send
    raise SSLError(e, request=request)
pip._vendor.requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)

(myvenv) C:\Users\nayana\djangogirls>pip install --upgrade urllib3
Collecting urllib3
  Could not fetch URL https://pypi.python.org/simple/urllib3/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
  Could not find a version that satisfies the requirement urllib3 (from versions: )
No matching distribution found for urllib3

(myvenv) C:\Users\nayana\djangogirls>pip --version
pip 9.0.1 from c:\users\nayana\djangogirls\myvenv\lib\site-packages (python 3.6)

(myvenv) C:\Users\nayana\djangogirls>pip install --trusterd-host=pypi.python --upgrade pip

Usage:
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

no such option: --trusterd-host

(myvenv) C:\Users\nayana\djangogirls>pip install --trusted-host=pypi.python --upgrade pip
Could not fetch URL https://pypi.python.org/simple/pip/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
Requirement already up-to-date: pip in c:\users\nayana\djangogirls\myvenv\lib\site-packages

(myvenv) C:\Users\nayana\djangogirls>pip install --trusted-host=pypi.python.org --upgrade pip
Requirement already up-to-date: pip in c:\users\nayana\djangogirls\myvenv\lib\site-packages

(myvenv) C:\Users\nayana\djangogirls>pip install --trusted-host=pypi.python.org django==1.10
Collecting django==1.10
  Downloading Django-1.10-py2.py3-none-any.whl
     \ 17.8MB 1.4MB/s
Installing collected packages: django
Successfully installed django-1.10

(myvenv) C:\Users\nayana\djangogirls>
(myvenv) C:\Users\nayana\djangogirls>
(myvenv) C:\Users\nayana\djangogirls>whoami
desktop-tk50ank\nayana

(myvenv) C:\Users\nayana\djangogirls>python
Python 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> 2+3
5
>>> 2**3
8
>>> "nayana"
'nayana'
>>> "nayana"+"l"
'nayanal'
>>> "nayana"*3
'nayananayananayana'
>>> "nayana".upper()
'NAYANA'
>>> len("nayana")
6
>>> len(str(446))
3
>>> name="nayana"
>>> name
'nayana'
>>> len(name)
6
>>> print(name)
nayana
>>> name
'nayana'
>>> []
[]
>>> sweets=[2 , 6 7]
  File "<stdin>", line 1
    sweets=[2 , 6 7]
                  ^
SyntaxError: invalid syntax
>>> sweets=[2 , 6, 7]
>>> sweets.sort()
>>> print(sweets)
[2, 6, 7]
>>> sweets.reverse9)
  File "<stdin>", line 1
    sweets.reverse9)
                   ^
SyntaxError: invalid syntax
>>> sweets.reverse()
>>> print(sweets)
[7, 6, 2]
>>> sweets.append()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: append() takes exactly one argument (0 given)
>>> sweets.append(25)
>>> print(sweets)
[7, 6, 2, 25]
>>> sweets.pop(2)
2
>>> print(sweets)
[7, 6, 25]
>>> student={'name:'nayana','place':'kerala'}
  File "<stdin>", line 1
    student={'name:'nayana','place':'kerala'}
                         ^
SyntaxError: invalid syntax
>>> student={'name':'nayana','place':'kerala'}
>>> print(student['name'])
nayana
>>> student['lang']=python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'python' is not defined
>>> student['lang']='python'
>>> student
{'name': 'nayana', 'place': 'kerala', 'lang': 'python'}
>>> len(student)
3
>>> student.pop(place)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'place' is not defined
>>> student.pop('place')
'kerala'
>>> student
{'name': 'nayana', 'lang': 'python'}
>>> 6>=12/2
True
>>> apple and orange
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'apple' is not defined
>>> True and True
True
>>> True and False
False
>>> exit()

(myvenv) C:\Users\nayana\djangogirls>cd C:\Users\nayana\Desktop

(myvenv) C:\Users\nayana\Desktop>python3 new.py
'python3' is not recognized as an internal or external command,
operable program or batch file.

(myvenv) C:\Users\nayana\Desktop>python3 new.py
'python3' is not recognized as an internal or external command,
operable program or batch file.

(myvenv) C:\Users\nayana\Desktop>python new.py
hello

(myvenv) C:\Users\nayana\Desktop>python
Python 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()

(myvenv) C:\Users\nayana\Desktop>python new.py
It works!

(myvenv) C:\Users\nayana\Desktop>python new.py
Hey Sonja!

(myvenv) C:\Users\nayana\Desktop>python new.py
  File "new.py", line 2
    print(hi)
        ^
IndentationError: expected an indented block

(myvenv) C:\Users\nayana\Desktop>python new.py
  File "new.py", line 2
    print(hi)
        ^
IndentationError: expected an indented block

(myvenv) C:\Users\nayana\Desktop>python new.py
  File "new.py", line 2
    print('hi')
        ^
IndentationError: expected an indented block

(myvenv) C:\Users\nayana\Desktop>python new.py
hi
helo

(myvenv) C:\Users\nayana\Desktop>python new.py
hi
helo

(myvenv) C:\Users\nayana\Desktop>python new.py
Traceback (most recent call last):
  File "new.py", line 6, in <module>
    hi()
TypeError: hi() missing 1 required positional argument: 'name'

(myvenv) C:\Users\nayana\Desktop>python new.py
Traceback (most recent call last):
  File "new.py", line 8, in <module>
    hi()
TypeError: hi() missing 1 required positional argument: 'name'

(myvenv) C:\Users\nayana\Desktop>python new.py
Traceback (most recent call last):
  File "new.py", line 8, in <module>
    hi()
TypeError: hi() missing 1 required positional argument: 'nayana'

(myvenv) C:\Users\nayana\Desktop>python new.py
Traceback (most recent call last):
  File "new.py", line 8, in <module>
    hi(nayana)
NameError: name 'nayana' is not defined

(myvenv) C:\Users\nayana\Desktop>python new.py
hi

(myvenv) C:\Users\nayana\Desktop>python new.py
  File "new.py", line 2
    print("hi"+name+"!")
        ^
IndentationError: expected an indented block

(myvenv) C:\Users\nayana\Desktop>python new.py
Traceback (most recent call last):
  File "new.py", line 4, in <module>
    hi(nayana)
NameError: name 'nayana' is not defined

(myvenv) C:\Users\nayana\Desktop>python new.py
hinayana!

(myvenv) C:\Users\nayana\Desktop>python new.py
hinayana!
next gal

(myvenv) C:\Users\nayana\Desktop>python new.py
  File "new.py", line 7
    for name in girls
                    ^
SyntaxError: invalid syntax

(myvenv) C:\Users\nayana\Desktop>python new.py
hinayana!
next gal
hinayana!
next gal
hinayana!
next gal

(myvenv) C:\Users\nayana\Desktop>python new.py
  File "new.py", line 1
    for i in range(1,6)
                      ^
SyntaxError: invalid syntax

(myvenv) C:\Users\nayana\Desktop>python new.py
1
2
3
4
5

(myvenv) C:\Users\nayana\Desktop>djngo-admin.py startproject mysite .
'djngo-admin.py' is not recognized as an internal or external command,
operable program or batch file.

(myvenv) C:\Users\nayana\Desktop>django-admin.py startproject mysite .

(myvenv) C:\Users\nayana\Desktop>mysite/setting.py
'mysite' is not recognized as an internal or external command,
operable program or batch file.

(myvenv) C:\Users\nayana\Desktop>django-admin.py startproject mysite .
CommandError: C:\Users\nayana\Desktop\manage.py already exists, overlaying a project or app into an existing directory won't replace conflicting files

(myvenv) C:\Users\nayana\Desktop>django-admin.py startproject mysite .
CommandError: C:\Users\nayana\Desktop\manage.py already exists, overlaying a project or app into an existing directory won't replace conflicting files

(myvenv) C:\Users\nayana\Desktop>django-admin.py startproject mysite .
CommandError: C:\Users\nayana\Desktop\manage.py already exists, overlaying a project or app into an existing directory won't replace conflicting files

(myvenv) C:\Users\nayana\Desktop>mysite/setting.py
'mysite' is not recognized as an internal or external command,
operable program or batch file.

(myvenv) C:\Users\nayana\Desktop>django-admin.py startproject mysite .

(myvenv) C:\Users\nayana\Desktop>dir
 Volume in drive C is OS
 Volume Serial Number is D6BD-931E

 Directory of C:\Users\nayana\Desktop

22-Jan-17  12:29 PM    <DIR>          .
22-Jan-17  12:29 PM    <DIR>          ..
22-Jan-17  08:49 AM             2,288 Atom.lnk
19-Jan-17  01:18 AM       104,284,200 AtomSetup.exe
22-Jan-17  09:09 AM               772 Desktop - Shortcut.lnk
20-Jan-17  12:49 PM       742,558,197 dhangal.mkv
22-Jan-17  12:28 PM    <DIR>          django
23-Jul-16  07:10 PM             1,106 KMPlayer.lnk
22-Jan-17  12:29 PM               804 manage.py
22-Jan-17  12:29 PM    <DIR>          mysite
22-Jan-17  12:16 PM                34 new.py
18-Jan-17  10:22 PM        31,505,640 python-3.6.0-amd64.exe
13-Dec-16  07:44 PM           105,922 resume1.pdf
23-Jul-16  06:57 PM             1,224 Youtube Downloader HD.lnk
              10 File(s)    878,460,187 bytes
               4 Dir(s)  183,955,378,176 bytes free

(myvenv) C:\Users\nayana\Desktop>python manage.py migrate
python: can't open file 'manage.py': [Errno 2] No such file or directory

(myvenv) C:\Users\nayana\Desktop>dir
 Volume in drive C is OS
 Volume Serial Number is D6BD-931E

 Directory of C:\Users\nayana\Desktop

22-Jan-17  12:30 PM    <DIR>          .
22-Jan-17  12:30 PM    <DIR>          ..
22-Jan-17  08:49 AM             2,288 Atom.lnk
19-Jan-17  01:18 AM       104,284,200 AtomSetup.exe
22-Jan-17  09:09 AM               772 Desktop - Shortcut.lnk
20-Jan-17  12:49 PM       742,558,197 dhangal.mkv
22-Jan-17  12:28 PM    <DIR>          django
23-Jul-16  07:10 PM             1,106 KMPlayer.lnk
22-Jan-17  12:16 PM                34 new.py
18-Jan-17  10:22 PM        31,505,640 python-3.6.0-amd64.exe
13-Dec-16  07:44 PM           105,922 resume1.pdf
23-Jul-16  06:57 PM             1,224 Youtube Downloader HD.lnk
               9 File(s)    878,459,383 bytes
               3 Dir(s)  184,097,792,000 bytes free

(myvenv) C:\Users\nayana\Desktop>cd django

(myvenv) C:\Users\nayana\Desktop\django>dir
 Volume in drive C is OS
 Volume Serial Number is D6BD-931E

 Directory of C:\Users\nayana\Desktop\django

22-Jan-17  12:28 PM    <DIR>          .
22-Jan-17  12:28 PM    <DIR>          ..
22-Jan-17  12:23 PM               804 manage.py
22-Jan-17  12:23 PM    <DIR>          mysite
               1 File(s)            804 bytes
               3 Dir(s)  184,097,787,904 bytes free

(myvenv) C:\Users\nayana\Desktop\django>python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, sessions
Running migrations:
  Rendering model states... DONE
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying sessions.0001_initial... OK

(myvenv) C:\Users\nayana\Desktop\django>python manage.py runserver
Performing system checks...

System check identified no issues (0 silenced).
January 22, 2017 - 12:49:20
Django version 1.10, using settings 'mysite.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
[22/Jan/2017 12:52:59] "GET / HTTP/1.1" 200 1767
Not Found: /favicon.ico
[22/Jan/2017 12:52:59] "GET /favicon.ico HTTP/1.1" 404 1936
Not Found: /favicon.ico
[22/Jan/2017 12:52:59] "GET /favicon.ico HTTP/1.1" 404 1936












































































































































































































































































































































































































C:\Users\nayana>mkdirdjangogirls
'mkdirdjangogirls' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\nayana>mkdir djangogirls

C:\Users\nayana>cd djangogirls

C:\Users\nayana\djangogirls> C:\Users\nayana\AppData\Local\Programs\Python\Python36\python -m venv myvenv

C:\Users\nayana\djangogirls>myvenv\Scripts\activate
(myvenv) C:\Users\nayana\djangogirls>pip install --upgrade pip
Could not fetch URL https://pypi.python.org/simple/pip/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
Requirement already up-to-date: pip in c:\users\nayana\djangogirls\myvenv\lib\site-packages

(myvenv) C:\Users\nayana\djangogirls>pip install django~=1.10.0
Collecting django~=1.10.0
  Could not fetch URL https://pypi.python.org/simple/django/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
  Could not find a version that satisfies the requirement django~=1.10.0 (from versions: )
No matching distribution found for django~=1.10.0

(myvenv) C:\Users\nayana\djangogirls>pip install --upgrade pip
Could not fetch URL https://pypi.python.org/simple/pip/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
Requirement already up-to-date: pip in c:\users\nayana\djangogirls\myvenv\lib\site-packages

(myvenv) C:\Users\nayana\djangogirls>pip install
You must give at least one requirement to install (see "pip help install")

(myvenv) C:\Users\nayana\djangogirls>pip install --upgrade pip
Could not fetch URL https://pypi.python.org/simple/pip/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
Requirement already up-to-date: pip in c:\users\nayana\djangogirls\myvenv\lib\site-packages

(myvenv) C:\Users\nayana\djangogirls>pip install --upgrade pip
Could not fetch URL https://pypi.python.org/simple/pip/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
Requirement already up-to-date: pip in c:\users\nayana\djangogirls\myvenv\lib\site-packages

(myvenv) C:\Users\nayana\djangogirls>pip install django~=1.10.0
Collecting django~=1.10.0
  Could not fetch URL https://pypi.python.org/simple/django/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
  Could not find a version that satisfies the requirement django~=1.10.0 (from versions: )
No matching distribution found for django~=1.10.0

(myvenv) C:\Users\nayana\djangogirls>pip install django~=1.10.0
Collecting django~=1.10.0
  Could not fetch URL https://pypi.python.org/simple/django/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
  Could not find a version that satisfies the requirement django~=1.10.0 (from versions: )
No matching distribution found for django~=1.10.0

(myvenv) C:\Users\nayana\djangogirls>pip install --upgrade pip
Could not fetch URL https://pypi.python.org/simple/pip/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
Requirement already up-to-date: pip in c:\users\nayana\djangogirls\myvenv\lib\site-packages

(myvenv) C:\Users\nayana\djangogirls>python -m pip install django~=1.10.0
Collecting django~=1.10.0
  Could not fetch URL https://pypi.python.org/simple/django/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
  Could not find a version that satisfies the requirement django~=1.10.0 (from versions: )
No matching distribution found for django~=1.10.0

(myvenv) C:\Users\nayana\djangogirls>python -m pip install django~=1.10.0
Collecting django~=1.10.0
  Could not fetch URL https://pypi.python.org/simple/django/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
  Could not find a version that satisfies the requirement django~=1.10.0 (from versions: )
No matching distribution found for django~=1.10.0

(myvenv) C:\Users\nayana\djangogirls>python -m pip install django~=1.10.0
Collecting django~=1.10.0
  Could not fetch URL https://pypi.python.org/simple/django/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
  Could not find a version that satisfies the requirement django~=1.10.0 (from versions: )
No matching distribution found for django~=1.10.0

(myvenv) C:\Users\nayana\djangogirls>python -m pip install django~=1.10.0
Collecting django~=1.10.0
  Could not fetch URL https://pypi.python.org/simple/django/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
  Could not find a version that satisfies the requirement django~=1.10.0 (from versions: )
No matching distribution found for django~=1.10.0

(myvenv) C:\Users\nayana\djangogirls>python -m pip install django~=1.10.0
Collecting django~=1.10.0
  Could not fetch URL https://pypi.python.org/simple/django/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
  Could not find a version that satisfies the requirement django~=1.10.0 (from versions: )
No matching distribution found for django~=1.10.0

(myvenv) C:\Users\nayana\djangogirls>pip install --upgrade pip
Could not fetch URL https://pypi.python.org/simple/pip/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
Requirement already up-to-date: pip in c:\users\nayana\djangogirls\myvenv\lib\site-packages

(myvenv) C:\Users\nayana\djangogirls>python
Python 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()

(myvenv) C:\Users\nayana\djangogirls>python -m pip install django~=1.10.1
Collecting django~=1.10.1
  Could not fetch URL https://pypi.python.org/simple/django/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
  Could not find a version that satisfies the requirement django~=1.10.1 (from versions: )
No matching distribution found for django~=1.10.1

(myvenv) C:\Users\nayana\djangogirls>pip install django~=1.
Invalid requirement: 'django~=1.'
Traceback (most recent call last):
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\packaging\requirements.py", line 92, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\pyparsing.py", line 1617, in parseString
    raise exc
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\pyparsing.py", line 1607, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\pyparsing.py", line 3376, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\pyparsing.py", line 1383, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\pyparsing.py", line 3164, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pip._vendor.pyparsing.ParseException: Expected stringEnd (at char 6), (line:1, col:7)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\req\req_install.py", line 82, in __init__
    req = Requirement(req)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\packaging\requirements.py", line 96, in __init__
    requirement_string[e.loc:e.loc + 8]))
pip._vendor.packaging.requirements.InvalidRequirement: Invalid requirement, parse error at "'~=1.'"


(myvenv) C:\Users\nayana\djangogirls>pip install django~=1.10.1
Collecting django~=1.10.1
  Could not fetch URL https://pypi.python.org/simple/django/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
  Could not find a version that satisfies the requirement django~=1.10.1 (from versions: )
No matching distribution found for django~=1.10.1

(myvenv) C:\Users\nayana\djangogirls>pip install django~=1.10.0
Collecting django~=1.10.0
  Could not fetch URL https://pypi.python.org/simple/django/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
  Could not find a version that satisfies the requirement django~=1.10.0 (from versions: )
No matching distribution found for django~=1.10.0

(myvenv) C:\Users\nayana\djangogirls>pip install django==1.10.0
Collecting django==1.10.0
  Could not fetch URL https://pypi.python.org/simple/django/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
  Could not find a version that satisfies the requirement django==1.10.0 (from versions: )
No matching distribution found for django==1.10.0

(myvenv) C:\Users\nayana\djangogirls>pip3 install django~=1.10.0
Collecting django~=1.10.0
  Could not fetch URL https://pypi.python.org/simple/django/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
  Could not find a version that satisfies the requirement django~=1.10.0 (from versions: )
No matching distribution found for django~=1.10.0

(myvenv) C:\Users\nayana\djangogirls>pip3 install django~=1.10.0
Collecting django~=1.10.0
  Could not fetch URL https://pypi.python.org/simple/django/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
  Could not find a version that satisfies the requirement django~=1.10.0 (from versions: )
No matching distribution found for django~=1.10.0

(myvenv) C:\Users\nayana\djangogirls>pip install django==1.10.0
Collecting django==1.10.0
  Could not fetch URL https://pypi.python.org/simple/django/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
  Could not find a version that satisfies the requirement django==1.10.0 (from versions: )
No matching distribution found for django==1.10.0

(myvenv) C:\Users\nayana\djangogirls>pip install Django~=1.10.0
Collecting Django~=1.10.0
  Could not fetch URL https://pypi.python.org/simple/django/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
  Could not find a version that satisfies the requirement Django~=1.10.0 (from versions: )
No matching distribution found for Django~=1.10.0

(myvenv) C:\Users\nayana\djangogirls>pip install Django==1.10.0
Collecting Django==1.10.0
  Could not fetch URL https://pypi.python.org/simple/django/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
  Could not find a version that satisfies the requirement Django==1.10.0 (from versions: )
No matching distribution found for Django==1.10.0

(myvenv) C:\Users\nayana\djangogirls>pip install Django
Collecting Django
  Could not fetch URL https://pypi.python.org/simple/django/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
  Could not find a version that satisfies the requirement Django (from versions: )
No matching distribution found for Django

(myvenv) C:\Users\nayana\djangogirls>pip install django
Collecting django
  Could not fetch URL https://pypi.python.org/simple/django/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
  Could not find a version that satisfies the requirement django (from versions: )
No matching distribution found for django

(myvenv) C:\Users\nayana\djangogirls>ping google.com

Pinging google.com [172.217.26.174] with 32 bytes of data:
Reply from 172.217.26.174: bytes=32 time=73ms TTL=56
Reply from 172.217.26.174: bytes=32 time=69ms TTL=56
Reply from 172.217.26.174: bytes=32 time=69ms TTL=56

Ping statistics for 172.217.26.174:
    Packets: Sent = 3, Received = 3, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 69ms, Maximum = 73ms, Average = 70ms
Control-C
^C
(myvenv) C:\Users\nayana\djangogirls>python3
'python3' is not recognized as an internal or external command,
operable program or batch file.

(myvenv) C:\Users\nayana\djangogirls>python
Python 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()

(myvenv) C:\Users\nayana\djangogirls>pip install --upgrade pip
Could not fetch URL https://pypi.python.org/simple/pip/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
Requirement already up-to-date: pip in c:\users\nayana\djangogirls\myvenv\lib\site-packages

(myvenv) C:\Users\nayana\djangogirls>easy_install pip
Searching for pip
Best match: pip 9.0.1
Adding pip 9.0.1 to easy-install.pth file
Installing pip-script.py script to c:\users\nayana\djangogirls\myvenv\Scripts
Installing pip.exe script to c:\users\nayana\djangogirls\myvenv\Scripts
Installing pip3-script.py script to c:\users\nayana\djangogirls\myvenv\Scripts
Installing pip3.exe script to c:\users\nayana\djangogirls\myvenv\Scripts
Installing pip3.5-script.py script to c:\users\nayana\djangogirls\myvenv\Scripts
Installing pip3.5.exe script to c:\users\nayana\djangogirls\myvenv\Scripts

Using c:\users\nayana\djangogirls\myvenv\lib\site-packages
Processing dependencies for pip
Finished processing dependencies for pip

(myvenv) C:\Users\nayana\djangogirls>pip install Django==1.10.0
Collecting Django==1.10.0
  Could not fetch URL https://pypi.python.org/simple/django/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
  Could not find a version that satisfies the requirement Django==1.10.0 (from versions: )
No matching distribution found for Django==1.10.0

(myvenv) C:\Users\nayana\djangogirls>pip --version
pip 9.0.1 from c:\users\nayana\djangogirls\myvenv\lib\site-packages (python 3.6)

(myvenv) C:\Users\nayana\djangogirls>pip --version
Traceback (most recent call last):
  File "C:\Users\nayana\djangogirls\myvenv\Scripts\pip-script.py", line 6, in <module>
    from pkg_resources import load_entry_point
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pkg_resources\__init__.py", line 36, in <module>
    import email.parser
  File "C:\Users\nayana\AppData\Local\Programs\Python\Python36\lib\email\parser.py", line 12, in <module>
    from email.feedparser import FeedParser, BytesFeedParser
  File "C:\Users\nayana\AppData\Local\Programs\Python\Python36\lib\email\feedparser.py", line 27, in <module>
    from email._policybase import compat32
  File "C:\Users\nayana\AppData\Local\Programs\Python\Python36\lib\email\_policybase.py", line 9, in <module>
    from email.utils import _has_surrogates
  File "C:\Users\nayana\AppData\Local\Programs\Python\Python36\lib\email\utils.py", line 28, in <module>
    import random
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 764, in get_code
  File "<frozen importlib._bootstrap_external>", line 832, in get_data
KeyboardInterrupt

(myvenv) C:\Users\nayana\djangogirls>pip install Django==1.10.0
Collecting Django==1.10.0
  Could not fetch URL https://pypi.python.org/simple/django/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
  Could not find a version that satisfies the requirement Django==1.10.0 (from versions: )
No matching distribution found for Django==1.10.0

(myvenv) C:\Users\nayana\djangogirls>pip install -upgrade pip.

Usage:
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

no such option: -u

(myvenv) C:\Users\nayana\djangogirls>pip install --upgrade pip
Could not fetch URL https://pypi.python.org/simple/pip/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
Requirement already up-to-date: pip in c:\users\nayana\djangogirls\myvenv\lib\site-packages

(myvenv) C:\Users\nayana\djangogirls>pip install django~=1.10.0
Collecting django~=1.10.0
  Could not fetch URL https://pypi.python.org/simple/django/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
  Could not find a version that satisfies the requirement django~=1.10.0 (from versions: )
No matching distribution found for django~=1.10.0

(myvenv) C:\Users\nayana\djangogirls>pip install django~=1.10.0 -vv
Config variable 'Py_DEBUG' is unset, Python ABI tag may be incorrect
Config variable 'WITH_PYMALLOC' is unset, Python ABI tag may be incorrect
Collecting django~=1.10.0
  1 location(s) to search for versions of django:
  * https://pypi.python.org/simple/django/
  Getting page https://pypi.python.org/simple/django/
  Looking up "https://pypi.python.org/simple/django/" in the cache
  No cache entry available
  Starting new HTTPS connection (1): pypi.python.org
  Could not fetch URL https://pypi.python.org/simple/django/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
  Could not find a version that satisfies the requirement django~=1.10.0 (from versions: )
Cleaning up...
No matching distribution found for django~=1.10.0
Exception information:
Traceback (most recent call last):
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\commands\install.py", line 324, in run
    requirement_set.prepare_files(finder)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\req\req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\req\req_set.py", line 554, in _prepare_file
    require_hashes
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\req\req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\index.py", line 514, in find_requirement
    'No matching distribution found for %s' % req
pip.exceptions.DistributionNotFound: No matching distribution found for django~=1.10.0
Looking up "https://pypi.python.org/pypi/pip/json" in the cache
No cache entry available
Starting new HTTPS connection (1): pypi.python.org
There was an error checking the latest version of pip
Traceback (most recent call last):
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\packages\urllib3\connectionpool.py", line 589, in urlopen
    self._prepare_proxy(conn)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\packages\urllib3\connectionpool.py", line 797, in _prepare_proxy
    conn.connect()
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\packages\urllib3\connection.py", line 289, in connect
    ssl_version=resolved_ssl_version)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\packages\urllib3\util\ssl_.py", line 308, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Users\nayana\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 401, in wrap_socket
    _context=self, _session=session)
  File "C:\Users\nayana\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 808, in __init__
    self.do_handshake()
  File "C:\Users\nayana\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 1061, in do_handshake
    self._sslobj.do_handshake()
  File "C:\Users\nayana\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 683, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\adapters.py", line 423, in send
    timeout=timeout
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\packages\urllib3\connectionpool.py", line 621, in urlopen
    raise SSLError(e)
pip._vendor.requests.packages.urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\utils\outdated.py", line 126, in pip_version_check
    headers={"Accept": "application/json"},
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\sessions.py", line 488, in get
    return self.request('GET', url, **kwargs)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\download.py", line 386, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\cachecontrol\adapter.py", line 47, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\adapters.py", line 497, in send
    raise SSLError(e, request=request)
pip._vendor.requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)

(myvenv) C:\Users\nayana\djangogirls>pip install django~=1.10.0 -vv
Config variable 'Py_DEBUG' is unset, Python ABI tag may be incorrect
Config variable 'WITH_PYMALLOC' is unset, Python ABI tag may be incorrect
Collecting django~=1.10.0
  1 location(s) to search for versions of django:
  * https://pypi.python.org/simple/django/
  Getting page https://pypi.python.org/simple/django/
  Looking up "https://pypi.python.org/simple/django/" in the cache
  No cache entry available
  Starting new HTTPS connection (1): pypi.python.org
  Could not fetch URL https://pypi.python.org/simple/django/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
  Could not find a version that satisfies the requirement django~=1.10.0 (from versions: )
Cleaning up...
No matching distribution found for django~=1.10.0
Exception information:
Traceback (most recent call last):
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\commands\install.py", line 324, in run
    requirement_set.prepare_files(finder)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\req\req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\req\req_set.py", line 554, in _prepare_file
    require_hashes
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\req\req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\index.py", line 514, in find_requirement
    'No matching distribution found for %s' % req
pip.exceptions.DistributionNotFound: No matching distribution found for django~=1.10.0
Looking up "https://pypi.python.org/pypi/pip/json" in the cache
No cache entry available
Starting new HTTPS connection (1): pypi.python.org
There was an error checking the latest version of pip
Traceback (most recent call last):
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\packages\urllib3\connectionpool.py", line 589, in urlopen
    self._prepare_proxy(conn)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\packages\urllib3\connectionpool.py", line 797, in _prepare_proxy
    conn.connect()
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\packages\urllib3\connection.py", line 289, in connect
    ssl_version=resolved_ssl_version)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\packages\urllib3\util\ssl_.py", line 308, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Users\nayana\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 401, in wrap_socket
    _context=self, _session=session)
  File "C:\Users\nayana\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 808, in __init__
    self.do_handshake()
  File "C:\Users\nayana\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 1061, in do_handshake
    self._sslobj.do_handshake()
  File "C:\Users\nayana\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 683, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\adapters.py", line 423, in send
    timeout=timeout
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\packages\urllib3\connectionpool.py", line 621, in urlopen
    raise SSLError(e)
pip._vendor.requests.packages.urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\utils\outdated.py", line 126, in pip_version_check
    headers={"Accept": "application/json"},
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\sessions.py", line 488, in get
    return self.request('GET', url, **kwargs)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\download.py", line 386, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\cachecontrol\adapter.py", line 47, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\adapters.py", line 497, in send
    raise SSLError(e, request=request)
pip._vendor.requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)

(myvenv) C:\Users\nayana\djangogirls>pip install django~=1.10.0 -vv
Config variable 'Py_DEBUG' is unset, Python ABI tag may be incorrect
Config variable 'WITH_PYMALLOC' is unset, Python ABI tag may be incorrect
Collecting django~=1.10.0
  1 location(s) to search for versions of django:
  * https://pypi.python.org/simple/django/
  Getting page https://pypi.python.org/simple/django/
  Looking up "https://pypi.python.org/simple/django/" in the cache
  No cache entry available
  Starting new HTTPS connection (1): pypi.python.org
  Could not fetch URL https://pypi.python.org/simple/django/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
  Could not find a version that satisfies the requirement django~=1.10.0 (from versions: )
Cleaning up...
No matching distribution found for django~=1.10.0
Exception information:
Traceback (most recent call last):
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\commands\install.py", line 324, in run
    requirement_set.prepare_files(finder)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\req\req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\req\req_set.py", line 554, in _prepare_file
    require_hashes
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\req\req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\index.py", line 514, in find_requirement
    'No matching distribution found for %s' % req
pip.exceptions.DistributionNotFound: No matching distribution found for django~=1.10.0
Looking up "https://pypi.python.org/pypi/pip/json" in the cache
No cache entry available
Starting new HTTPS connection (1): pypi.python.org
There was an error checking the latest version of pip
Traceback (most recent call last):
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\packages\urllib3\connectionpool.py", line 589, in urlopen
    self._prepare_proxy(conn)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\packages\urllib3\connectionpool.py", line 797, in _prepare_proxy
    conn.connect()
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\packages\urllib3\connection.py", line 289, in connect
    ssl_version=resolved_ssl_version)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\packages\urllib3\util\ssl_.py", line 308, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Users\nayana\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 401, in wrap_socket
    _context=self, _session=session)
  File "C:\Users\nayana\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 808, in __init__
    self.do_handshake()
  File "C:\Users\nayana\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 1061, in do_handshake
    self._sslobj.do_handshake()
  File "C:\Users\nayana\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 683, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\adapters.py", line 423, in send
    timeout=timeout
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\packages\urllib3\connectionpool.py", line 621, in urlopen
    raise SSLError(e)
pip._vendor.requests.packages.urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\utils\outdated.py", line 126, in pip_version_check
    headers={"Accept": "application/json"},
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\sessions.py", line 488, in get
    return self.request('GET', url, **kwargs)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\download.py", line 386, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\cachecontrol\adapter.py", line 47, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\adapters.py", line 497, in send
    raise SSLError(e, request=request)
pip._vendor.requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)

(myvenv) C:\Users\nayana\djangogirls>pip install django~=1.10.0
Collecting django~=1.10.0
  Could not fetch URL https://pypi.python.org/simple/django/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
  Could not find a version that satisfies the requirement django~=1.10.0 (from versions: )
No matching distribution found for django~=1.10.0

(myvenv) C:\Users\nayana\djangogirls>pip install django==1.10 -vv
Config variable 'Py_DEBUG' is unset, Python ABI tag may be incorrect
Config variable 'WITH_PYMALLOC' is unset, Python ABI tag may be incorrect
Collecting django==1.10
  1 location(s) to search for versions of django:
  * https://pypi.python.org/simple/django/
  Getting page https://pypi.python.org/simple/django/
  Looking up "https://pypi.python.org/simple/django/" in the cache
  No cache entry available
  Starting new HTTPS connection (1): pypi.python.org
  Could not fetch URL https://pypi.python.org/simple/django/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
  Could not find a version that satisfies the requirement django==1.10 (from versions: )
Cleaning up...
No matching distribution found for django==1.10
Exception information:
Traceback (most recent call last):
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\commands\install.py", line 324, in run
    requirement_set.prepare_files(finder)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\req\req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\req\req_set.py", line 554, in _prepare_file
    require_hashes
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\req\req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\index.py", line 514, in find_requirement
    'No matching distribution found for %s' % req
pip.exceptions.DistributionNotFound: No matching distribution found for django==1.10
Looking up "https://pypi.python.org/pypi/pip/json" in the cache
No cache entry available
Starting new HTTPS connection (1): pypi.python.org
There was an error checking the latest version of pip
Traceback (most recent call last):
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\packages\urllib3\connectionpool.py", line 589, in urlopen
    self._prepare_proxy(conn)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\packages\urllib3\connectionpool.py", line 797, in _prepare_proxy
    conn.connect()
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\packages\urllib3\connection.py", line 289, in connect
    ssl_version=resolved_ssl_version)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\packages\urllib3\util\ssl_.py", line 308, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Users\nayana\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 401, in wrap_socket
    _context=self, _session=session)
  File "C:\Users\nayana\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 808, in __init__
    self.do_handshake()
  File "C:\Users\nayana\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 1061, in do_handshake
    self._sslobj.do_handshake()
  File "C:\Users\nayana\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 683, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\adapters.py", line 423, in send
    timeout=timeout
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\packages\urllib3\connectionpool.py", line 621, in urlopen
    raise SSLError(e)
pip._vendor.requests.packages.urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\utils\outdated.py", line 126, in pip_version_check
    headers={"Accept": "application/json"},
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\sessions.py", line 488, in get
    return self.request('GET', url, **kwargs)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\download.py", line 386, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\cachecontrol\adapter.py", line 47, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\adapters.py", line 497, in send
    raise SSLError(e, request=request)
pip._vendor.requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)

(myvenv) C:\Users\nayana\djangogirls>pip install --upgraded pip

Usage:
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

no such option: --upgraded

(myvenv) C:\Users\nayana\djangogirls>pip install --upgrade pip
Could not fetch URL https://pypi.python.org/simple/pip/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
Requirement already up-to-date: pip in c:\users\nayana\djangogirls\myvenv\lib\site-packages

(myvenv) C:\Users\nayana\djangogirls>pip install django==1.10 -vv
Config variable 'Py_DEBUG' is unset, Python ABI tag may be incorrect
Config variable 'WITH_PYMALLOC' is unset, Python ABI tag may be incorrect
Collecting django==1.10
  1 location(s) to search for versions of django:
  * https://pypi.python.org/simple/django/
  Getting page https://pypi.python.org/simple/django/
  Looking up "https://pypi.python.org/simple/django/" in the cache
  No cache entry available
  Starting new HTTPS connection (1): pypi.python.org
  Could not fetch URL https://pypi.python.org/simple/django/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
  Could not find a version that satisfies the requirement django==1.10 (from versions: )
Cleaning up...
No matching distribution found for django==1.10
Exception information:
Traceback (most recent call last):
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\commands\install.py", line 324, in run
    requirement_set.prepare_files(finder)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\req\req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\req\req_set.py", line 554, in _prepare_file
    require_hashes
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\req\req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\index.py", line 514, in find_requirement
    'No matching distribution found for %s' % req
pip.exceptions.DistributionNotFound: No matching distribution found for django==1.10
Looking up "https://pypi.python.org/pypi/pip/json" in the cache
No cache entry available
Starting new HTTPS connection (1): pypi.python.org
There was an error checking the latest version of pip
Traceback (most recent call last):
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\packages\urllib3\connectionpool.py", line 589, in urlopen
    self._prepare_proxy(conn)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\packages\urllib3\connectionpool.py", line 797, in _prepare_proxy
    conn.connect()
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\packages\urllib3\connection.py", line 289, in connect
    ssl_version=resolved_ssl_version)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\packages\urllib3\util\ssl_.py", line 308, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Users\nayana\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 401, in wrap_socket
    _context=self, _session=session)
  File "C:\Users\nayana\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 808, in __init__
    self.do_handshake()
  File "C:\Users\nayana\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 1061, in do_handshake
    self._sslobj.do_handshake()
  File "C:\Users\nayana\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 683, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\adapters.py", line 423, in send
    timeout=timeout
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\packages\urllib3\connectionpool.py", line 621, in urlopen
    raise SSLError(e)
pip._vendor.requests.packages.urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\utils\outdated.py", line 126, in pip_version_check
    headers={"Accept": "application/json"},
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\sessions.py", line 488, in get
    return self.request('GET', url, **kwargs)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\download.py", line 386, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\cachecontrol\adapter.py", line 47, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "c:\users\nayana\djangogirls\myvenv\lib\site-packages\pip\_vendor\requests\adapters.py", line 497, in send
    raise SSLError(e, request=request)
pip._vendor.requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)

(myvenv) C:\Users\nayana\djangogirls>pip install --upgrade urllib3
Collecting urllib3
  Could not fetch URL https://pypi.python.org/simple/urllib3/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
  Could not find a version that satisfies the requirement urllib3 (from versions: )
No matching distribution found for urllib3

(myvenv) C:\Users\nayana\djangogirls>pip --version
pip 9.0.1 from c:\users\nayana\djangogirls\myvenv\lib\site-packages (python 3.6)

(myvenv) C:\Users\nayana\djangogirls>pip install --trusterd-host=pypi.python --upgrade pip

Usage:
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

no such option: --trusterd-host

(myvenv) C:\Users\nayana\djangogirls>pip install --trusted-host=pypi.python --upgrade pip
Could not fetch URL https://pypi.python.org/simple/pip/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
Requirement already up-to-date: pip in c:\users\nayana\djangogirls\myvenv\lib\site-packages

(myvenv) C:\Users\nayana\djangogirls>pip install --trusted-host=pypi.python.org --upgrade pip
Requirement already up-to-date: pip in c:\users\nayana\djangogirls\myvenv\lib\site-packages

(myvenv) C:\Users\nayana\djangogirls>pip install --trusted-host=pypi.python.org django==1.10
Collecting django==1.10
  Downloading Django-1.10-py2.py3-none-any.whl
     \ 17.8MB 1.4MB/s
Installing collected packages: django
Successfully installed django-1.10

(myvenv) C:\Users\nayana\djangogirls>
(myvenv) C:\Users\nayana\djangogirls>
(myvenv) C:\Users\nayana\djangogirls>whoami
desktop-tk50ank\nayana

(myvenv) C:\Users\nayana\djangogirls>python
Python 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> 2+3
5
>>> 2**3
8
>>> "nayana"
'nayana'
>>> "nayana"+"l"
'nayanal'
>>> "nayana"*3
'nayananayananayana'
>>> "nayana".upper()
'NAYANA'
>>> len("nayana")
6
>>> len(str(446))
3
>>> name="nayana"
>>> name
'nayana'
>>> len(name)
6
>>> print(name)
nayana
>>> name
'nayana'
>>> []
[]
>>> sweets=[2 , 6 7]
  File "<stdin>", line 1
    sweets=[2 , 6 7]
                  ^
SyntaxError: invalid syntax
>>> sweets=[2 , 6, 7]
>>> sweets.sort()
>>> print(sweets)
[2, 6, 7]
>>> sweets.reverse9)
  File "<stdin>", line 1
    sweets.reverse9)
                   ^
SyntaxError: invalid syntax
>>> sweets.reverse()
>>> print(sweets)
[7, 6, 2]
>>> sweets.append()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: append() takes exactly one argument (0 given)
>>> sweets.append(25)
>>> print(sweets)
[7, 6, 2, 25]
>>> sweets.pop(2)
2
>>> print(sweets)
[7, 6, 25]
>>> student={'name:'nayana','place':'kerala'}
  File "<stdin>", line 1
    student={'name:'nayana','place':'kerala'}
                         ^
SyntaxError: invalid syntax
>>> student={'name':'nayana','place':'kerala'}
>>> print(student['name'])
nayana
>>> student['lang']=python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'python' is not defined
>>> student['lang']='python'
>>> student
{'name': 'nayana', 'place': 'kerala', 'lang': 'python'}
>>> len(student)
3
>>> student.pop(place)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'place' is not defined
>>> student.pop('place')
'kerala'
>>> student
{'name': 'nayana', 'lang': 'python'}
>>> 6>=12/2
True
>>> apple and orange
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'apple' is not defined
>>> True and True
True
>>> True and False
False
>>> exit()

(myvenv) C:\Users\nayana\djangogirls>cd C:\Users\nayana\Desktop

(myvenv) C:\Users\nayana\Desktop>python3 new.py
'python3' is not recognized as an internal or external command,
operable program or batch file.

(myvenv) C:\Users\nayana\Desktop>python3 new.py
'python3' is not recognized as an internal or external command,
operable program or batch file.

(myvenv) C:\Users\nayana\Desktop>python new.py
hello

(myvenv) C:\Users\nayana\Desktop>python
Python 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()

(myvenv) C:\Users\nayana\Desktop>python new.py
It works!

(myvenv) C:\Users\nayana\Desktop>python new.py
Hey Sonja!

(myvenv) C:\Users\nayana\Desktop>python new.py
  File "new.py", line 2
    print(hi)
        ^
IndentationError: expected an indented block

(myvenv) C:\Users\nayana\Desktop>python new.py
  File "new.py", line 2
    print(hi)
        ^
IndentationError: expected an indented block

(myvenv) C:\Users\nayana\Desktop>python new.py
  File "new.py", line 2
    print('hi')
        ^
IndentationError: expected an indented block

(myvenv) C:\Users\nayana\Desktop>python new.py
hi
helo

(myvenv) C:\Users\nayana\Desktop>python new.py
hi
helo

(myvenv) C:\Users\nayana\Desktop>python new.py
Traceback (most recent call last):
  File "new.py", line 6, in <module>
    hi()
TypeError: hi() missing 1 required positional argument: 'name'

(myvenv) C:\Users\nayana\Desktop>python new.py
Traceback (most recent call last):
  File "new.py", line 8, in <module>
    hi()
TypeError: hi() missing 1 required positional argument: 'name'

(myvenv) C:\Users\nayana\Desktop>python new.py
Traceback (most recent call last):
  File "new.py", line 8, in <module>
    hi()
TypeError: hi() missing 1 required positional argument: 'nayana'

(myvenv) C:\Users\nayana\Desktop>python new.py
Traceback (most recent call last):
  File "new.py", line 8, in <module>
    hi(nayana)
NameError: name 'nayana' is not defined

(myvenv) C:\Users\nayana\Desktop>python new.py
hi

(myvenv) C:\Users\nayana\Desktop>python new.py
  File "new.py", line 2
    print("hi"+name+"!")
        ^
IndentationError: expected an indented block

(myvenv) C:\Users\nayana\Desktop>python new.py
Traceback (most recent call last):
  File "new.py", line 4, in <module>
    hi(nayana)
NameError: name 'nayana' is not defined

(myvenv) C:\Users\nayana\Desktop>python new.py
hinayana!

(myvenv) C:\Users\nayana\Desktop>python new.py
hinayana!
next gal

(myvenv) C:\Users\nayana\Desktop>python new.py
  File "new.py", line 7
    for name in girls
                    ^
SyntaxError: invalid syntax

(myvenv) C:\Users\nayana\Desktop>python new.py
hinayana!
next gal
hinayana!
next gal
hinayana!
next gal

(myvenv) C:\Users\nayana\Desktop>python new.py
  File "new.py", line 1
    for i in range(1,6)
                      ^
SyntaxError: invalid syntax

(myvenv) C:\Users\nayana\Desktop>python new.py
1
2
3
4
5

(myvenv) C:\Users\nayana\Desktop>djngo-admin.py startproject mysite .
'djngo-admin.py' is not recognized as an internal or external command,
operable program or batch file.

(myvenv) C:\Users\nayana\Desktop>django-admin.py startproject mysite .

(myvenv) C:\Users\nayana\Desktop>mysite/setting.py
'mysite' is not recognized as an internal or external command,
operable program or batch file.

(myvenv) C:\Users\nayana\Desktop>django-admin.py startproject mysite .
CommandError: C:\Users\nayana\Desktop\manage.py already exists, overlaying a project or app into an existing directory won't replace conflicting files

(myvenv) C:\Users\nayana\Desktop>django-admin.py startproject mysite .
CommandError: C:\Users\nayana\Desktop\manage.py already exists, overlaying a project or app into an existing directory won't replace conflicting files

(myvenv) C:\Users\nayana\Desktop>django-admin.py startproject mysite .
CommandError: C:\Users\nayana\Desktop\manage.py already exists, overlaying a project or app into an existing directory won't replace conflicting files

(myvenv) C:\Users\nayana\Desktop>mysite/setting.py
'mysite' is not recognized as an internal or external command,
operable program or batch file.

(myvenv) C:\Users\nayana\Desktop>django-admin.py startproject mysite .

(myvenv) C:\Users\nayana\Desktop>dir
 Volume in drive C is OS
 Volume Serial Number is D6BD-931E

 Directory of C:\Users\nayana\Desktop

22-Jan-17  12:29 PM    <DIR>          .
22-Jan-17  12:29 PM    <DIR>          ..
22-Jan-17  08:49 AM             2,288 Atom.lnk
19-Jan-17  01:18 AM       104,284,200 AtomSetup.exe
22-Jan-17  09:09 AM               772 Desktop - Shortcut.lnk
20-Jan-17  12:49 PM       742,558,197 dhangal.mkv
22-Jan-17  12:28 PM    <DIR>          django
23-Jul-16  07:10 PM             1,106 KMPlayer.lnk
22-Jan-17  12:29 PM               804 manage.py
22-Jan-17  12:29 PM    <DIR>          mysite
22-Jan-17  12:16 PM                34 new.py
18-Jan-17  10:22 PM        31,505,640 python-3.6.0-amd64.exe
13-Dec-16  07:44 PM           105,922 resume1.pdf
23-Jul-16  06:57 PM             1,224 Youtube Downloader HD.lnk
              10 File(s)    878,460,187 bytes
               4 Dir(s)  183,955,378,176 bytes free

(myvenv) C:\Users\nayana\Desktop>python manage.py migrate
python: can't open file 'manage.py': [Errno 2] No such file or directory

(myvenv) C:\Users\nayana\Desktop>dir
 Volume in drive C is OS
 Volume Serial Number is D6BD-931E

 Directory of C:\Users\nayana\Desktop

22-Jan-17  12:30 PM    <DIR>          .
22-Jan-17  12:30 PM    <DIR>          ..
22-Jan-17  08:49 AM             2,288 Atom.lnk
19-Jan-17  01:18 AM       104,284,200 AtomSetup.exe
22-Jan-17  09:09 AM               772 Desktop - Shortcut.lnk
20-Jan-17  12:49 PM       742,558,197 dhangal.mkv
22-Jan-17  12:28 PM    <DIR>          django
23-Jul-16  07:10 PM             1,106 KMPlayer.lnk
22-Jan-17  12:16 PM                34 new.py
18-Jan-17  10:22 PM        31,505,640 python-3.6.0-amd64.exe
13-Dec-16  07:44 PM           105,922 resume1.pdf
23-Jul-16  06:57 PM             1,224 Youtube Downloader HD.lnk
               9 File(s)    878,459,383 bytes
               3 Dir(s)  184,097,792,000 bytes free

(myvenv) C:\Users\nayana\Desktop>cd django

(myvenv) C:\Users\nayana\Desktop\django>dir
 Volume in drive C is OS
 Volume Serial Number is D6BD-931E

 Directory of C:\Users\nayana\Desktop\django

22-Jan-17  12:28 PM    <DIR>          .
22-Jan-17  12:28 PM    <DIR>          ..
22-Jan-17  12:23 PM               804 manage.py
22-Jan-17  12:23 PM    <DIR>          mysite
               1 File(s)            804 bytes
               3 Dir(s)  184,097,787,904 bytes free

(myvenv) C:\Users\nayana\Desktop\django>python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, sessions
Running migrations:
  Rendering model states... DONE
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying sessions.0001_initial... OK

(myvenv) C:\Users\nayana\Desktop\django>python manage.py runserver
Performing system checks...

System check identified no issues (0 silenced).
January 22, 2017 - 12:49:20
Django version 1.10, using settings 'mysite.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
[22/Jan/2017 12:52:59] "GET / HTTP/1.1" 200 1767
Not Found: /favicon.ico
[22/Jan/2017 12:52:59] "GET /favicon.ico HTTP/1.1" 404 1936
Not Found: /favicon.ico
[22/Jan/2017 12:52:59] "GET /favicon.ico HTTP/1.1" 404 1936











































































































































































































































































































































































































































































































































































































































































